# Generated by Django 4.1.2 on 2022-10-19 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrobase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='material_block_images')),
            ],
        ),
        migrations.RenameField(
            model_name='materialimage',
            old_name='material_id',
            new_name='material',
        ),
        migrations.AlterField(
            model_name='material',
            name='category',
            field=models.CharField(choices=[('1', 'Болезни'), ('2', 'Насекомые')], max_length=125),
        ),
        migrations.AlterField(
            model_name='materialimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='material_images'),
        ),
        migrations.DeleteModel(
            name='MaterialBlog',
        ),
        migrations.AddField(
            model_name='materialblock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_blogs', to='agrobase.material'),
        ),
    ]
