# Generated by Django 4.1.2 on 2022-10-19 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agrobase', '0002_materialblock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialblock',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_blocks', to='agrobase.material'),
        ),
    ]
