# Generated by Django 4.1.2 on 2023-02-14 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('my_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profiles', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('full_name', models.CharField(max_length=55)),
                ('phone_number', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name_plural': 'Профиль',
            },
        ),
    ]
