# Generated by Django 4.1.2 on 2023-02-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_myuser_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
    ]
