# Generated by Django 4.1.2 on 2023-04-26 05:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_my_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('text', models.CharField(max_length=100, verbose_name='Текст уведомления')),
                ('text_ru', models.CharField(max_length=100, null=True, verbose_name='Текст уведомления')),
                ('text_ky', models.CharField(max_length=100, null=True, verbose_name='Текст уведомления')),
                ('text_en', models.CharField(max_length=100, null=True, verbose_name='Текст уведомления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
