# Generated by Django 4.1.2 on 2023-03-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_image', models.BigIntegerField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='bin')),
                ('container_type', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='тип емкости')),
                ('container_color', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='цвет емкости')),
                ('missing_wheel', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='отсутствие колеса')),
                ('container_upside_down', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='емкость перевернута')),
                ('integrity_container_broken', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='целостность емкости нарушена')),
                ('traces_damage_containers_fire', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='наличие следов повреждения емкости огнем')),
                ('hull_damage', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='повреждение корпуса')),
                ('damage_structural_elements_waste_generation', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='повреждения конструкционных элементов для погрузки отходов')),
                ('smoke', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='дым')),
                ('fire', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='огонь')),
                ('type_of_waste', models.CharField(blank=True, default='Неизвестно', max_length=125, null=True, verbose_name='вид отходов (КГО/ТКО/РСО/Строительные отходы)')),
                ('object_quantity', models.CharField(blank=True, max_length=10, null=True, verbose_name='Колличество распознанных объектов')),
                ('percent', models.CharField(blank=True, max_length=255, null=True, verbose_name='Процент')),
            ],
        ),
    ]
