# Generated by Django 4.1.2 on 2023-08-22 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auditlog', '0015_alter_logentry_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Создано'), (1, 'Обновлено'), (2, 'Удалено'), (3, 'Доступно')], db_index=True, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='additional_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='changes',
            field=models.JSONField(null=True, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='changes_text',
            field=models.TextField(blank=True, verbose_name='Текст изменения'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='cid',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='ID корреляции'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='object_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='object_pk',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='object_repr',
            field=models.TextField(verbose_name='Представление'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='remote_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Дистанционный адрес'),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Время'),
        ),
    ]
