# Generated by Django 4.1.2 on 2023-09-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auditlog', '0016_alter_logentry_action_alter_logentry_actor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logentry',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp'], 'verbose_name': 'Журнал изменения', 'verbose_name_plural': 'Журнал изменений'},
        ),
        migrations.AlterField(
            model_name='logentry',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='Тип контента'),
        ),
    ]
