# Generated by Django 3.2 on 2022-10-12 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plot', '0002_auto_20221012_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plot',
            name='geometry',
        ),
        migrations.AlterField(
            model_name='plot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to=settings.AUTH_USER_MODEL),
        ),
    ]
