# Generated by Django 3.2 on 2022-10-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0003_auto_20221012_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='culture',
            name='start',
            field=models.DateField(),
        ),
    ]
