# Generated by Django 3.2 on 2022-10-13 07:27

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0004_auto_20221012_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='geometry',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
