# Generated by Django 3.2 on 2022-10-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0005_culture_geometry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('unit', models.CharField(max_length=55)),
                ('start', models.DateField()),
                ('end', models.DateField(blank=True, null=True)),
                ('culture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='plot.culture')),
            ],
        ),
    ]
