# Generated by Django 3.2 on 2022-10-14 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0006_crop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Culture',
            new_name='CultureField',
        ),
    ]
