# Generated by Django 4.1.2 on 2022-10-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0007_rename_culture_culturefield'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ('-start',)},
        ),
        migrations.AlterModelOptions(
            name='culturefield',
            options={'ordering': ('-start',)},
        ),
    ]
