# Generated by Django 4.1.2 on 2022-10-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0008_alter_crop_options_alter_culturefield_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('day_of_fertilizer', models.DateField()),
                ('culture_field', models.ManyToManyField(to='plot.culturefield')),
            ],
        ),
    ]
