# Generated by Django 4.1.2 on 2022-11-01 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0008_alter_crop_options_alter_culturefield_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='soil_analysis')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('culture_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_analysis', to='plot.culturefield')),
            ],
        ),
    ]
