# Generated by Django 4.1.2 on 2022-11-01 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plot', '0009_fertilizer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturefield',
            name='plot',
        ),
        migrations.AddField(
            model_name='culturefield',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
