# Generated by Django 4.1.2 on 2022-11-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0009_soilanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilanalysis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
