# Generated by Django 4.1.2 on 2022-11-01 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plot', '0010_alter_soilanalysis_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culturefield',
            name='plot',
        ),
        migrations.AddField(
            model_name='culturefield',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('day_of_fertilizer', models.DateField()),
                ('culture_field', models.ManyToManyField(to='plot.culturefield')),
            ],
        ),
    ]
