# Generated by Django 4.1.2 on 2022-11-02 11:06

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plot', '0011_remove_culturefield_plot_culturefield_owner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldPolygon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('is_actual', models.BooleanField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygon_field', to='plot.field')),
            ],
        ),
        migrations.RemoveField(
            model_name='crop',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='fertilizer',
            name='culture_field',
        ),
        migrations.RemoveField(
            model_name='soilanalysis',
            name='culture_field',
        ),
        migrations.DeleteModel(
            name='CultureField',
        ),
        migrations.AddField(
            model_name='crop',
            name='field',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crops', to='plot.field'),
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='field',
            field=models.ManyToManyField(to='plot.field'),
        ),
        migrations.AddField(
            model_name='soilanalysis',
            name='field',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='soil_analysis', to='plot.field'),
            preserve_default=False,
        ),
    ]
