# Generated by Django 4.1.2 on 2022-11-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plot', '0014_remove_soilanalysis_field_soilanalysis_field_polygon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={},
        ),
        migrations.RemoveField(
            model_name='crop',
            name='end',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='field',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='start',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='what',
        ),
        migrations.AddField(
            model_name='crop',
            name='field_in_season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plot.fieldinseason'),
            preserve_default=False,
        ),
    ]
