# Generated by Django 4.1.2 on 2023-01-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gip', '0011_culture_fill_color_culture_stroke_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Decade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='IndexPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=3, default=0, max_digits=5)),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='gip.culture')),
                ('decade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.decade')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.index')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.phase')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='gip.region')),
            ],
        ),
    ]
