# Generated by Django 4.1.2 on 2023-01-06 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0011_culture_fill_color_culture_stroke_color_and_more'),
        ('culture_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decade',
            options={'verbose_name': 'Декада', 'verbose_name_plural': 'Декады'},
        ),
        migrations.AlterModelOptions(
            name='index',
            options={'verbose_name': 'Индекс', 'verbose_name_plural': 'Индексы'},
        ),
        migrations.AlterModelOptions(
            name='indexplan',
            options={'verbose_name': 'Плановое значение индекса', 'verbose_name_plural': 'плановые значение индексов'},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'verbose_name': 'Фаза развития', 'verbose_name_plural': 'Фазы развития'},
        ),
        migrations.AlterField(
            model_name='decade',
            name='end_date',
            field=models.DateField(verbose_name='по'),
        ),
        migrations.AlterField(
            model_name='decade',
            name='start_date',
            field=models.DateField(verbose_name='с'),
        ),
        migrations.AlterField(
            model_name='index',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='gip.culture', verbose_name='культуа'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.decade', verbose_name='декада'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.index', verbose_name='индекс'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.phase', verbose_name='фаза'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='gip.region', verbose_name='область'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='значение индекса'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Название'),
        ),
    ]
