# Generated by Django 4.1.2 on 2023-01-23 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0011_productivityclass_historicalproductivityclass_and_more'),
        ('culture_model', '0002_alter_decade_options_alter_index_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Index',
            new_name='VegetationIndex',
        ),
    ]
