# Generated by Django 4.1.2 on 2023-02-22 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0019_alter_contouryear_contour_alter_contouryear_type'),
        ('culture_model', '0003_rename_index_vegetationindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decade',
            options={'verbose_name': 'Decade', 'verbose_name_plural': 'Decades'},
        ),
        migrations.AlterModelOptions(
            name='indexplan',
            options={'verbose_name': 'Planned index value', 'verbose_name_plural': 'Planned index values'},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'verbose_name': 'Development phase', 'verbose_name_plural': 'Development phases'},
        ),
        migrations.AlterModelOptions(
            name='vegetationindex',
            options={'verbose_name': 'Index', 'verbose_name_plural': 'Indexes'},
        ),
        migrations.AddField(
            model_name='phase',
            name='name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='phase',
            name='name_ky',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='phase',
            name='name_ru',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='vegetationindex',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vegetationindex',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vegetationindex',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='vegetationindex',
            name='name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='vegetationindex',
            name='name_ky',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='vegetationindex',
            name='name_ru',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='decade',
            name='end_date',
            field=models.DateField(verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='decade',
            name='start_date',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='gip.culture', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.decade', verbose_name='Decade'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.vegetationindex', verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.phase', verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='gip.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Index value'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Name'),
        ),
    ]
