# Generated by Django 4.1.2 on 2023-05-24 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0051_contour_predicted_productivity_and_more'),
        ('culture_model', '0005_alter_decade_options_alter_indexplan_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'description')},
            },
        ),
        migrations.CreateModel(
            name='GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Subclass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('classes', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclasses', to='culture_model.classes')),
            ],
            options={
                'unique_together': {('name', 'description', 'classes')},
            },
        ),
        migrations.CreateModel(
            name='RepublicanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('type_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='republican_type', to='culture_model.grouptype')),
            ],
            options={
                'unique_together': {('name', 'description', 'type_group')},
            },
        ),
        migrations.AddField(
            model_name='grouptype',
            name='subclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_type', to='culture_model.subclass'),
        ),
        migrations.CreateModel(
            name='PastureCulture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255)),
                ('coefficient_to_productivity', models.DecimalField(decimal_places=2, max_digits=4)),
                ('content_of_feed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('district_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasture_culture', to='gip.district')),
            ],
            options={
                'unique_together': {('district_type', 'name', 'coefficient_to_productivity', 'content_of_feed')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grouptype',
            unique_together={('name', 'description', 'subclass')},
        ),
        migrations.CreateModel(
            name='DistrictType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.district')),
                ('type_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_type', to='culture_model.republicantype')),
            ],
            options={
                'unique_together': {('type_group', 'name', 'description', 'district')},
            },
        ),
    ]
