# Generated by Django 4.1.2 on 2023-05-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_model', '0006_classes_grouptype_subclass_republicantype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastureculture',
            name='district_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasture_culture', to='culture_model.districttype'),
        ),
    ]
