# Generated by Django 4.1.2 on 2023-06-02 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0053_alter_contour_pasture_culture'),
        ('culture_model', '0007_alter_pastureculture_district_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Класс', 'verbose_name_plural': 'Классы'},
        ),
        migrations.AlterModelOptions(
            name='districttype',
            options={'verbose_name': 'Тип района', 'verbose_name_plural': 'Типы районов'},
        ),
        migrations.AlterModelOptions(
            name='grouptype',
            options={'verbose_name': 'Тип группы', 'verbose_name_plural': 'Типы группы'},
        ),
        migrations.AlterModelOptions(
            name='pastureculture',
            options={'verbose_name': 'Культура пастбища', 'verbose_name_plural': 'Культуры пастбищ'},
        ),
        migrations.AlterModelOptions(
            name='republicantype',
            options={'verbose_name': 'Тип растительности', 'verbose_name_plural': 'Типы растительностей'},
        ),
        migrations.AlterModelOptions(
            name='subclass',
            options={'verbose_name': 'Подкласс', 'verbose_name_plural': 'Подклассы'},
        ),
        migrations.AlterField(
            model_name='classes',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='districttype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='districttype',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='districttype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='districttype',
            name='type_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_type', to='culture_model.republicantype', verbose_name='Тип растительности'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='subclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_type', to='culture_model.subclass', verbose_name='Подкласс'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='coefficient_to_productivity',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Коэффициент продуктивности'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='content_of_feed',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Содержание корма'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='district_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasture_culture', to='culture_model.districttype', verbose_name='Тип района'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='republicantype',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='republicantype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='republicantype',
            name='type_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='republican_type', to='culture_model.grouptype', verbose_name='Тип группы'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclasses', to='culture_model.classes', verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Название'),
        ),
    ]
