# Generated by Django 4.1.2 on 2023-06-05 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0053_alter_contour_pasture_culture'),
        ('culture_model', '0008_alter_classes_options_alter_districttype_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pastureculture',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pastureculture',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.district'),
        ),
        migrations.AddField(
            model_name='pastureculture',
            name='veg_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='culture_model.phase'),
        ),
        migrations.AlterUniqueTogether(
            name='pastureculture',
            unique_together={('district_type', 'name', 'coefficient_to_productivity', 'content_of_feed', 'district')},
        ),
    ]
