# Generated by Django 4.1.2 on 2023-06-06 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_model', '0009_alter_pastureculture_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastureculture',
            name='culture_ID',
            field=models.CharField(default=None, max_length=20),
            preserve_default=False,
        ),
    ]
