# Generated by Django 4.1.2 on 2023-06-20 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('culture_model', '0010_pastureculture_culture_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastureculture',
            name='culture_ID',
        ),
    ]
