# Generated by Django 4.1.2 on 2023-09-23 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0063_contour_vegetation_type_and_more'),
        ('culture_model', '0012_alter_pastureculture_district_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classes',
            options={'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
        migrations.AlterModelOptions(
            name='decade',
            options={'verbose_name': 'Decade', 'verbose_name_plural': 'Decades'},
        ),
        migrations.AlterModelOptions(
            name='districttype',
            options={'verbose_name': 'District Type', 'verbose_name_plural': 'District Types'},
        ),
        migrations.AlterModelOptions(
            name='grouptype',
            options={'verbose_name': 'Group Type', 'verbose_name_plural': 'Group Types'},
        ),
        migrations.AlterModelOptions(
            name='indexplan',
            options={'verbose_name': 'Planned Index Value', 'verbose_name_plural': 'Planned Index Values'},
        ),
        migrations.AlterModelOptions(
            name='pastureculture',
            options={'verbose_name': 'Pasture Culture', 'verbose_name_plural': 'Pasture Cultures'},
        ),
        migrations.AlterModelOptions(
            name='phase',
            options={'verbose_name': 'Development Phase', 'verbose_name_plural': 'Development Phases'},
        ),
        migrations.AlterModelOptions(
            name='republicantype',
            options={'verbose_name': 'Vegetation Type', 'verbose_name_plural': 'Vegetation Types'},
        ),
        migrations.AlterModelOptions(
            name='subclass',
            options={'verbose_name': 'Subclass', 'verbose_name_plural': 'Subclasses'},
        ),
        migrations.AlterModelOptions(
            name='vegetationindex',
            options={'verbose_name': 'Vegetation Index', 'verbose_name_plural': 'Vegetation Indices'},
        ),
        migrations.AlterField(
            model_name='classes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='decade',
            name='end_date',
            field=models.DateField(verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='decade',
            name='start_date',
            field=models.DateField(verbose_name='From'),
        ),
        migrations.AlterField(
            model_name='districttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='districttype',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='districttype',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='districttype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='districttype',
            name='type_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='district_type', to='culture_model.republicantype', verbose_name='Vegetation Type'),
        ),
        migrations.AlterField(
            model_name='districttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='subclass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_type', to='culture_model.subclass', verbose_name='Subclass'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='gip.culture', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='decade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.decade', verbose_name='Decade'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.vegetationindex', verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='culture_model.phase', verbose_name='Phase'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='index_plans', to='gip.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='indexplan',
            name='value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Index Value'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='coefficient_to_productivity',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Productivity Coefficient'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='content_of_feed',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Feed Content'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='district_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pasture_culture', to='culture_model.districttype', verbose_name='District Type'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='pastureculture',
            name='veg_period',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='culture_model.phase', verbose_name='Vegetation Period'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Development Phase'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='Development Phase'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name_ky',
            field=models.CharField(max_length=125, null=True, verbose_name='Development Phase'),
        ),
        migrations.AlterField(
            model_name='phase',
            name='name_ru',
            field=models.CharField(max_length=125, null=True, verbose_name='Development Phase'),
        ),
        migrations.AlterField(
            model_name='republicantype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='republicantype',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='republicantype',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='republicantype',
            name='type_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='republican_type', to='culture_model.grouptype', verbose_name='Group Type'),
        ),
        migrations.AlterField(
            model_name='republicantype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='classes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclasses', to='culture_model.classes', verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='subclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='name_ky',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='vegetationindex',
            name='name_ru',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
    ]
