# Generated by Django 4.1.2 on 2022-11-16 10:12

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('conton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='gip.conton')),
            ],
        ),
        migrations.CreateModel(
            name='Culture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('coefficient_crop', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_inn', models.CharField(max_length=14)),
                ('mobile', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fertility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LandUse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('season', models.IntegerField(blank=True, null=True)),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_uses', to='gip.contour')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_uses', to='gip.culture')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_uses', to='gip.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='OrthoPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('layer_name', models.CharField(max_length=55)),
                ('url', models.URLField(max_length=1024)),
                ('use_y_n', models.BooleanField()),
                ('file', models.FileField(upload_to='ortho_photo')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('population', models.IntegerField()),
                ('area', models.IntegerField()),
                ('density', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SoilClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('fertility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_classes', to='gip.fertility')),
            ],
        ),
        migrations.CreateModel(
            name='SoilProductivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('conton', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='gip.conton')),
            ],
        ),
        migrations.CreateModel(
            name='SoilFertility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('soil_productivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_fertility', to='gip.soilproductivity')),
            ],
        ),
        migrations.CreateModel(
            name='SoilClassMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('soil_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_class_maps', to='gip.soilclass')),
            ],
        ),
        migrations.CreateModel(
            name='LandUsePhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='land_use_photos')),
                ('land_use', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_use_photos', to='gip.landuse')),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='gip.region')),
            ],
        ),
        migrations.CreateModel(
            name='CropYield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(help_text='Indicated in centners')),
                ('year', models.IntegerField()),
                ('season', models.IntegerField(blank=True, null=True)),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_yields', to='gip.contour')),
                ('culture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_yields', to='gip.culture')),
            ],
        ),
        migrations.AddField(
            model_name='contour',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='gip.farmer'),
        ),
        migrations.AddField(
            model_name='conton',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contons', to='gip.district'),
        ),
    ]
