# Generated by Django 4.1.2 on 2022-11-24 12:02

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contour',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography='Kyrgyzstan', srid=4326),
        ),
    ]
