# Generated by Django 4.1.2 on 2022-11-24 12:06

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0002_alter_contour_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conton',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography='Kyrgyzstan', srid=4326),
        ),
        migrations.AlterField(
            model_name='district',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography='Kyrgyzstan', srid=4326),
        ),
        migrations.AlterField(
            model_name='soilclassmap',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography='Kyrgyzstan', srid=4326),
        ),
        migrations.AlterField(
            model_name='soilfertility',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography='Kyrgyzstan', srid=4326),
        ),
        migrations.AlterField(
            model_name='village',
            name='polygon',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(geography='Kyrgyzstan', srid=4326),
        ),
    ]
