# Generated by Django 4.1.2 on 2022-11-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0007_alter_contour_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contour',
            name='ink',
            field=models.CharField(help_text='Идентификационный Номер Контура', max_length=100, null=True, verbose_name='ИНК'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='ink',
            field=models.CharField(help_text='Идентификационный Номер Контура', max_length=100, null=True, verbose_name='ИНК'),
        ),
    ]
