# Generated by Django 4.1.2 on 2022-11-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0008_contour_ink_historicalcontour_ink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contour',
            name='ink',
            field=models.CharField(help_text='Идентификационный Номер Контура', max_length=100, null=True, unique=True, verbose_name='ИНК'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='ink',
            field=models.CharField(db_index=True, help_text='Идентификационный Номер Контура', max_length=100, null=True, verbose_name='ИНК'),
        ),
    ]
