# Generated by Django 4.1.2 on 2022-12-19 08:31

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0009_alter_contour_ink_alter_historicalcontour_ink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conton',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='district',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclassmap',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalsoilfertility',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalvillage',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='soilclassmap',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='soilfertility',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='village',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
    ]
