# Generated by Django 4.1.2 on 2022-12-26 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0010_alter_conton_polygon_alter_contour_polygon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='fill_color',
            field=models.CharField(default='#3388FF', max_length=55),
        ),
        migrations.AddField(
            model_name='culture',
            name='stroke_color',
            field=models.CharField(default='#3388FF', max_length=55),
        ),
        migrations.AddField(
            model_name='historicalculture',
            name='fill_color',
            field=models.CharField(default='#3388FF', max_length=55),
        ),
        migrations.AddField(
            model_name='historicalculture',
            name='stroke_color',
            field=models.CharField(default='#3388FF', max_length=55),
        ),
    ]
