# Generated by Django 4.1.2 on 2023-01-20 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0011_culture_fill_color_culture_stroke_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125, verbose_name='Название')),
            ],
        ),
        migrations.RenameField(
            model_name='contour',
            old_name='sum_ha',
            new_name='area_ha',
        ),
        migrations.RenameField(
            model_name='historicalcontour',
            old_name='sum_ha',
            new_name='area_ha',
        ),
        migrations.AddField(
            model_name='contour',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contours', to='gip.landtype'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.landtype'),
        ),
    ]
