# Generated by Django 4.1.2 on 2023-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0012_landtype_rename_sum_ha_contour_area_ha_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landtype',
            options={'verbose_name': 'Тип земли ', 'verbose_name_plural': 'Типы земель'},
        ),
        migrations.AddField(
            model_name='contour',
            name='is_rounded',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='is_rounded',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
