# Generated by Django 4.1.2 on 2023-02-07 10:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0014_historicalregion_polygon_region_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='conton',
            name='code_soato',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Код СОАТО'),
        ),
        migrations.AddField(
            model_name='district',
            name='code_soato',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Код СОАТО'),
        ),
        migrations.AddField(
            model_name='historicalconton',
            name='code_soato',
            field=models.CharField(db_index=True, max_length=30, null=True, verbose_name='Код СОАТО'),
        ),
        migrations.AddField(
            model_name='historicaldistrict',
            name='code_soato',
            field=models.CharField(db_index=True, max_length=30, null=True, verbose_name='Код СОАТО'),
        ),
        migrations.AddField(
            model_name='historicalregion',
            name='code_soato',
            field=models.CharField(db_index=True, max_length=30, null=True, verbose_name='Код СОАТО'),
        ),
        migrations.AddField(
            model_name='region',
            name='code_soato',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Контур'),
        ),
    ]
