# Generated by Django 4.1.2 on 2023-02-07 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0017_alter_conton_code_soato_alter_contour_code_soato_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contouryear',
            options={'verbose_name': 'Контуры поля по годам', 'verbose_name_plural': 'Контуры полей по годам'},
        ),
        migrations.RemoveField(
            model_name='cropyield',
            name='contour',
        ),
        migrations.RemoveField(
            model_name='historicalcropyield',
            name='contour',
        ),
        migrations.AddField(
            model_name='cropyield',
            name='contour_year',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crop_yields', to='gip.contouryear', verbose_name='Поле'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcropyield',
            name='contour_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contouryear', verbose_name='Поле'),
        ),
    ]
