# Generated by Django 4.1.2 on 2023-02-08 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0018_alter_contouryear_options_remove_cropyield_contour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contouryear',
            name='contour',
            field=models.ManyToManyField(related_name='contour_year', to='gip.contour', verbose_name='Контуры полей'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_year', to='gip.landtype'),
        ),
    ]
