# Generated by Django 4.1.2 on 2023-02-22 06:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0020_alter_conton_options_alter_historicalconton_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contour',
            options={'verbose_name': "Field's contours", 'verbose_name_plural': "Fields' contours"},
        ),
        migrations.AlterModelOptions(
            name='contouryear',
            options={'verbose_name': "Field's contours by years", 'verbose_name_plural': "Fields' contours by years"},
        ),
        migrations.AlterModelOptions(
            name='historicalcontour',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History', 'verbose_name_plural': "historical Fields' contours"},
        ),
        migrations.AlterModelOptions(
            name='landtype',
            options={'verbose_name': 'Land type', 'verbose_name_plural': 'Land types'},
        ),
        migrations.AddField(
            model_name='contouryear',
            name='productivity_en',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contouryear',
            name='productivity_ky',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='contouryear',
            name='productivity_ru',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='landtype',
            name='name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='landtype',
            name='name_ky',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='landtype',
            name='name_ru',
            field=models.CharField(max_length=125, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='SOATO code'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='conton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='gip.conton', verbose_name='Aiyl aimag'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='gip.farmer', verbose_name='Farmer'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='ink',
            field=models.CharField(blank=True, help_text='Loop identification number', max_length=100, null=True, unique=True, verbose_name='ИНК'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='area_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area per hectare'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='SOATO code'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='contour',
            field=models.ManyToManyField(related_name='contour_year', to='gip.contour', verbose_name="Fields' contours"),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='code_soato',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='SOATO code'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='conton',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.conton', verbose_name='Aiyl aimag'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='farmer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.farmer', verbose_name='Farmer'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='ink',
            field=models.CharField(blank=True, db_index=True, help_text='Loop identification number', max_length=100, null=True, verbose_name='ИНК'),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Name'),
        ),
    ]
