# Generated by Django 4.1.2 on 2023-02-22 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0021_alter_contour_options_alter_contouryear_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropyield',
            options={'verbose_name': 'Productivity', 'verbose_name_plural': 'Productivity'},
        ),
        migrations.AlterModelOptions(
            name='culture',
            options={'verbose_name': 'Culture', 'verbose_name_plural': 'Cultures'},
        ),
        migrations.AlterModelOptions(
            name='historicalcropyield',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Productivity', 'verbose_name_plural': 'historical Productivity'},
        ),
        migrations.AlterModelOptions(
            name='historicalculture',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Culture', 'verbose_name_plural': 'historical Cultures'},
        ),
        migrations.AddField(
            model_name='culture',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AddField(
            model_name='culture',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AddField(
            model_name='culture',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='contour_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_yields', to='gip.contouryear', verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_yields', to='gip.culture', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='weight',
            field=models.FloatField(help_text='Indicated in centners', verbose_name='Productivity'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='coefficient_crop',
            field=models.FloatField(verbose_name='Yield coefficient'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='contour_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contouryear', verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='culture',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.culture', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='weight',
            field=models.FloatField(help_text='Indicated in centners', verbose_name='Productivity'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='coefficient_crop',
            field=models.FloatField(verbose_name='Yield coefficient'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Culture'),
        ),
    ]
