# Generated by Django 4.1.2 on 2023-02-22 09:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0022_alter_cropyield_options_alter_culture_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='historicaldistrict',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical District', 'verbose_name_plural': 'historical Districts'},
        ),
        migrations.AddField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='district',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Soato code'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=55, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='gip.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='code_soato',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Soato code'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='name',
            field=models.CharField(max_length=55, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.region', verbose_name='Region'),
        ),
    ]
