# Generated by Django 4.1.2 on 2023-02-22 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gip', '0023_alter_district_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'Farmer', 'verbose_name_plural': 'Farmers'},
        ),
        migrations.AlterModelOptions(
            name='fertility',
            options={'verbose_name': 'Fertilizer', 'verbose_name_plural': 'Fertilizers'},
        ),
        migrations.AlterModelOptions(
            name='historicalfarmer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Farmer', 'verbose_name_plural': 'historical Farmers'},
        ),
        migrations.AlterModelOptions(
            name='historicalfertility',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Fertilizer', 'verbose_name_plural': 'historical Fertilizers'},
        ),
        migrations.AddField(
            model_name='fertility',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Fertilizer'),
        ),
        migrations.AddField(
            model_name='fertility',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Fertilizer'),
        ),
        migrations.AddField(
            model_name='fertility',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Fertilizer'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='pin_inn',
            field=models.CharField(max_length=14, verbose_name='PIN or INN'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to=settings.AUTH_USER_MODEL, verbose_name='Farmer'),
        ),
        migrations.AlterField(
            model_name='fertility',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Fertilizer'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='pin_inn',
            field=models.CharField(max_length=14, verbose_name='PIN or INN'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Farmer'),
        ),
        migrations.AlterField(
            model_name='historicalfertility',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Fertilizer'),
        ),
    ]
