# Generated by Django 4.1.2 on 2023-02-22 10:08

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0025_alter_historicallanduse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalregion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Region', 'verbose_name_plural': 'historical Regions'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Region name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Region name'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Region name'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='area',
            field=models.IntegerField(verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='code_soato',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='SOATO code'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='density',
            field=models.FloatField(verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Region name'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='population',
            field=models.IntegerField(verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='region',
            name='area',
            field=models.IntegerField(verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='SOATO code'),
        ),
        migrations.AlterField(
            model_name='region',
            name='density',
            field=models.FloatField(verbose_name='density'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Region name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Polygon'),
        ),
        migrations.AlterField(
            model_name='region',
            name='population',
            field=models.IntegerField(verbose_name='Population'),
        ),
    ]
