# Generated by Django 4.1.2 on 2023-02-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0028_alter_conton_options_alter_historicalconton_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contouryear',
            name='productivity_en',
        ),
        migrations.RemoveField(
            model_name='contouryear',
            name='productivity_ky',
        ),
        migrations.RemoveField(
            model_name='contouryear',
            name='productivity_ru',
        ),
    ]
