# Generated by Django 4.1.2 on 2023-02-28 04:44

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gip', '0029_remove_contouryear_productivity_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conton',
            options={'verbose_name': 'Округ', 'verbose_name_plural': 'Округи'},
        ),
        migrations.AlterModelOptions(
            name='contour',
            options={'verbose_name': 'Контуры поля', 'verbose_name_plural': 'Контуры полей'},
        ),
        migrations.AlterModelOptions(
            name='contouryear',
            options={'verbose_name': 'Контуры поля по годам', 'verbose_name_plural': 'Контуры полей по годам'},
        ),
        migrations.AlterModelOptions(
            name='cropyield',
            options={'verbose_name': 'Продуктивность', 'verbose_name_plural': 'Продуктивность'},
        ),
        migrations.AlterModelOptions(
            name='culture',
            options={'verbose_name': 'Культура', 'verbose_name_plural': 'Культуры'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'Фермер', 'verbose_name_plural': 'Фермеры'},
        ),
        migrations.AlterModelOptions(
            name='fertility',
            options={'verbose_name': 'Удобрение', 'verbose_name_plural': 'Удобрения'},
        ),
        migrations.AlterModelOptions(
            name='historicalconton',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Округ', 'verbose_name_plural': 'historical Округи'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontour',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Контуры полей'},
        ),
        migrations.AlterModelOptions(
            name='historicalcropyield',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Продуктивность', 'verbose_name_plural': 'historical Продуктивность'},
        ),
        migrations.AlterModelOptions(
            name='historicalculture',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Культура', 'verbose_name_plural': 'historical Культуры'},
        ),
        migrations.AlterModelOptions(
            name='historicaldistrict',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Район', 'verbose_name_plural': 'historical Районы'},
        ),
        migrations.AlterModelOptions(
            name='historicalfarmer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Фермер', 'verbose_name_plural': 'historical Фермеры'},
        ),
        migrations.AlterModelOptions(
            name='historicalfertility',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Удобрение', 'verbose_name_plural': 'historical Удобрения'},
        ),
        migrations.AlterModelOptions(
            name='historicallanduse',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Землепользование', 'verbose_name_plural': 'historical Землепользование'},
        ),
        migrations.AlterModelOptions(
            name='historicallandusephotos',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Спутниковое изображение', 'verbose_name_plural': 'historical Спутниковые изображения'},
        ),
        migrations.AlterModelOptions(
            name='historicalorthophoto',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Спутниковое изображение', 'verbose_name_plural': 'historical Спутниковые изображения'},
        ),
        migrations.AlterModelOptions(
            name='historicalregion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Область', 'verbose_name_plural': 'historical Области'},
        ),
        migrations.AlterModelOptions(
            name='historicalsoilclass',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Тип почвы', 'verbose_name_plural': 'historical Типы почвы'},
        ),
        migrations.AlterModelOptions(
            name='historicalsoilclassmap',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Контур типа почвы', 'verbose_name_plural': 'historical Контуры типа почвы'},
        ),
        migrations.AlterModelOptions(
            name='historicalsoilfertility',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Плодородие почвы', 'verbose_name_plural': 'historical Плодородие почв'},
        ),
        migrations.AlterModelOptions(
            name='historicalsoilproductivity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Продуктивность почвы', 'verbose_name_plural': 'historical Продуктивность почв'},
        ),
        migrations.AlterModelOptions(
            name='historicalvillage',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Село', 'verbose_name_plural': 'historical Сёла'},
        ),
        migrations.AlterModelOptions(
            name='landtype',
            options={'verbose_name': 'Тип земли', 'verbose_name_plural': 'Типы земли'},
        ),
        migrations.AlterModelOptions(
            name='landuse',
            options={'verbose_name': 'Землепользование', 'verbose_name_plural': 'Землепользование'},
        ),
        migrations.AlterModelOptions(
            name='landusephotos',
            options={'verbose_name': 'Спутниковое изображение', 'verbose_name_plural': 'Спутниковые изображения'},
        ),
        migrations.AlterModelOptions(
            name='orthophoto',
            options={'verbose_name': 'Спутниковое изображение', 'verbose_name_plural': 'Спутниковые изображения'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Области'},
        ),
        migrations.AlterModelOptions(
            name='soilclass',
            options={'verbose_name': 'Тип почвы', 'verbose_name_plural': 'Типы почвы'},
        ),
        migrations.AlterModelOptions(
            name='soilclassmap',
            options={'verbose_name': 'Контур типа почвы', 'verbose_name_plural': 'Контуры типа почвы'},
        ),
        migrations.AlterModelOptions(
            name='soilfertility',
            options={'verbose_name': 'Плодородие почвы', 'verbose_name_plural': 'Плодородие почв'},
        ),
        migrations.AlterModelOptions(
            name='soilproductivity',
            options={'verbose_name': 'Продуктивность почвы', 'verbose_name_plural': 'Продуктивность почв'},
        ),
        migrations.AlterModelOptions(
            name='village',
            options={'verbose_name': 'Село', 'verbose_name_plural': 'Сёла'},
        ),
        migrations.AlterField(
            model_name='conton',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contons', to='gip.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='conton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='gip.conton', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='gip.farmer', verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='ink',
            field=models.CharField(blank=True, help_text='Идентификационный номер контура', max_length=100, null=True, unique=True, verbose_name='ИНК'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='area_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь в гектарах'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='contour',
            field=models.ManyToManyField(related_name='contour_year', to='gip.contour', verbose_name='Контуры полей'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='productivity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Продуктивность'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_year', to='gip.landtype', verbose_name='Тип земли'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='year',
            field=models.CharField(max_length=20, verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='contour_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_yields', to='gip.contouryear', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_yields', to='gip.culture', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='weight',
            field=models.FloatField(help_text='Измеряется в центнерах', verbose_name='Продуктивность'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='coefficient_crop',
            field=models.FloatField(verbose_name='Коэффициент продуктивности'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='fill_color',
            field=models.CharField(default='#3388FF', max_length=55, verbose_name='Цвет заливки'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='stroke_color',
            field=models.CharField(default='#3388FF', max_length=55, verbose_name='Цвет обводки'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='district',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='district',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='gip.region', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='pin_inn',
            field=models.CharField(help_text='Идентификационный номер налогоплательщика или Персональный идентификационный номер', max_length=14, verbose_name='ПИН или ИНН'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to=settings.AUTH_USER_MODEL, verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='fertility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='fertility',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Удобрение'),
        ),
        migrations.AlterField(
            model_name='fertility',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобрение'),
        ),
        migrations.AlterField(
            model_name='fertility',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобрение'),
        ),
        migrations.AlterField(
            model_name='fertility',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобрение'),
        ),
        migrations.AlterField(
            model_name='fertility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='code_soato',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='code_soato',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='conton',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.conton', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='farmer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.farmer', verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='ink',
            field=models.CharField(blank=True, db_index=True, help_text='Идентификационный номер контура', max_length=100, null=True, verbose_name='ИНК'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='contour_year',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contouryear', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='culture',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.culture', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='weight',
            field=models.FloatField(help_text='Измеряется в центнерах', verbose_name='Продуктивность'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='coefficient_crop',
            field=models.FloatField(verbose_name='Коэффициент продуктивности'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='fill_color',
            field=models.CharField(default='#3388FF', max_length=55, verbose_name='Цвет заливки'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='stroke_color',
            field=models.CharField(default='#3388FF', max_length=55, verbose_name='Цвет обводки'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='code_soato',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.region', verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='pin_inn',
            field=models.CharField(help_text='Идентификационный номер налогоплательщика или Персональный идентификационный номер', max_length=14, verbose_name='ПИН или ИНН'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='historicalfertility',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalfertility',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Удобрение'),
        ),
        migrations.AlterField(
            model_name='historicalfertility',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобрение'),
        ),
        migrations.AlterField(
            model_name='historicalfertility',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобрение'),
        ),
        migrations.AlterField(
            model_name='historicalfertility',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Удобрение'),
        ),
        migrations.AlterField(
            model_name='historicalfertility',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicallanduse',
            name='contour',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contour', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='historicallanduse',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicallanduse',
            name='culture',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.culture', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='historicallanduse',
            name='farmer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.farmer', verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='historicallanduse',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='historicallanduse',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicallanduse',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='historicallandusephotos',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicallandusephotos',
            name='image',
            field=models.TextField(max_length=100, verbose_name='Спутниковое изображение'),
        ),
        migrations.AlterField(
            model_name='historicallandusephotos',
            name='land_use',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.landuse', verbose_name='Землепользование'),
        ),
        migrations.AlterField(
            model_name='historicallandusephotos',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalorthophoto',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalorthophoto',
            name='file',
            field=models.TextField(max_length=100, verbose_name='Спутниковое изображение'),
        ),
        migrations.AlterField(
            model_name='historicalorthophoto',
            name='layer_name',
            field=models.CharField(max_length=55, verbose_name='Название слоя'),
        ),
        migrations.AlterField(
            model_name='historicalorthophoto',
            name='layer_name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Название слоя'),
        ),
        migrations.AlterField(
            model_name='historicalorthophoto',
            name='layer_name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Название слоя'),
        ),
        migrations.AlterField(
            model_name='historicalorthophoto',
            name='layer_name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Название слоя'),
        ),
        migrations.AlterField(
            model_name='historicalorthophoto',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalorthophoto',
            name='url',
            field=models.URLField(max_length=1024, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='historicalorthophoto',
            name='use_y_n',
            field=models.BooleanField(verbose_name='Используется'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='area',
            field=models.IntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='code_soato',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='density',
            field=models.FloatField(verbose_name='Плотность'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='population',
            field=models.IntegerField(verbose_name='Население'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='fertility',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.fertility', verbose_name='Удобрение'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclassmap',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclassmap',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclassmap',
            name='soil_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.soilclass', verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclassmap',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalsoilfertility',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalsoilfertility',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalsoilfertility',
            name='soil_productivity',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.soilproductivity', verbose_name='Плодородие почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilfertility',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Продуктивность почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Продуктивность почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Продуктивность почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Продуктивность почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicalvillage',
            name='conton',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.conton', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='historicalvillage',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicalvillage',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='historicalvillage',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='historicalvillage',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='historicalvillage',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='historicalvillage',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalvillage',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='name_ky',
            field=models.CharField(max_length=125, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='name_ru',
            field=models.CharField(max_length=125, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='landuse',
            name='contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_uses', to='gip.contour', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='landuse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='landuse',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_uses', to='gip.culture', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='landuse',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_uses', to='gip.farmer', verbose_name='Фермер'),
        ),
        migrations.AlterField(
            model_name='landuse',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Сезон'),
        ),
        migrations.AlterField(
            model_name='landuse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='landuse',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
        migrations.AlterField(
            model_name='landusephotos',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='landusephotos',
            name='image',
            field=models.FileField(upload_to='land_use_photos', verbose_name='Спутниковое изображение'),
        ),
        migrations.AlterField(
            model_name='landusephotos',
            name='land_use',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_use_photos', to='gip.landuse', verbose_name='Землепользование'),
        ),
        migrations.AlterField(
            model_name='landusephotos',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='orthophoto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='orthophoto',
            name='file',
            field=models.FileField(upload_to='ortho_photo', verbose_name='Спутниковое изображение'),
        ),
        migrations.AlterField(
            model_name='orthophoto',
            name='layer_name',
            field=models.CharField(max_length=55, verbose_name='Название слоя'),
        ),
        migrations.AlterField(
            model_name='orthophoto',
            name='layer_name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Название слоя'),
        ),
        migrations.AlterField(
            model_name='orthophoto',
            name='layer_name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Название слоя'),
        ),
        migrations.AlterField(
            model_name='orthophoto',
            name='layer_name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Название слоя'),
        ),
        migrations.AlterField(
            model_name='orthophoto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='orthophoto',
            name='url',
            field=models.URLField(max_length=1024, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='orthophoto',
            name='use_y_n',
            field=models.BooleanField(verbose_name='Используется'),
        ),
        migrations.AlterField(
            model_name='region',
            name='area',
            field=models.IntegerField(verbose_name='Площадь'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='region',
            name='density',
            field=models.FloatField(verbose_name='Плотность'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Область'),
        ),
        migrations.AlterField(
            model_name='region',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='region',
            name='population',
            field=models.IntegerField(verbose_name='Население'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='fertility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_classes', to='gip.fertility', verbose_name='Удобрение'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='soilclassmap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='soilclassmap',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='soilclassmap',
            name='soil_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_class_maps', to='gip.soilclass', verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='soilclassmap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='soilfertility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='soilfertility',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='soilfertility',
            name='soil_productivity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_fertility', to='gip.soilproductivity', verbose_name='Плодородие почвы'),
        ),
        migrations.AlterField(
            model_name='soilfertility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Продуктивность почвы'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Продуктивность почвы'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Продуктивность почвы'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Продуктивность почвы'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='village',
            name='conton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villages', to='gip.conton', verbose_name='Округ'),
        ),
        migrations.AlterField(
            model_name='village',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='village',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Село'),
        ),
        migrations.AlterField(
            model_name='village',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='village',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
