# Generated by Django 4.1.2 on 2023-02-28 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0030_alter_conton_options_alter_contour_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contour',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='contouryear',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
