# Generated by Django 4.1.2 on 2023-02-28 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0032_contouryear_culture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contour',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступный'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='is_rounded',
            field=models.BooleanField(default=False, verbose_name='Юридический подтвержденный'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.culture', verbose_name='Культура'),
        ),
        migrations.AlterField(
            model_name='contouryear',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступный'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Доступный'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='is_rounded',
            field=models.BooleanField(default=False, verbose_name='Юридический подтвержденный'),
        ),
    ]
