# Generated by Django 4.1.2 on 2023-02-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0033_alter_contour_is_available_alter_contour_is_rounded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contour',
            name='is_rounded',
            field=models.BooleanField(default=False, verbose_name='Юридически подтвержденный'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='is_rounded',
            field=models.BooleanField(default=False, verbose_name='Юридически подтвержденный'),
        ),
    ]
