# Generated by Django 4.1.2 on 2023-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0034_alter_contour_is_rounded_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contour',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='contouryear',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='historicalcontour',
            name='is_available',
        ),
        migrations.AddField(
            model_name='contour',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удаленный'),
        ),
        migrations.AddField(
            model_name='contouryear',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удаленный'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Удаленный'),
        ),
    ]
