# Generated by Django 4.1.2 on 2023-02-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0035_remove_contour_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsoilclass',
            name='fertility',
        ),
        migrations.RemoveField(
            model_name='soilclass',
            name='fertility',
        ),
        migrations.AddField(
            model_name='historicalsoilclass',
            name='ID',
            field=models.BigIntegerField(default=None, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsoilclass',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalsoilclass',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicalsoilclass',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicalsoilclass',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='soilclass',
            name='ID',
            field=models.BigIntegerField(default=None, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soilclass',
            name='description',
            field=models.TextField(default=None, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soilclass',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='soilclass',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='soilclass',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
