# Generated by Django 4.1.2 on 2023-02-28 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0036_remove_historicalsoilclass_fertility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soilclassmap',
            name='soil_class_en',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_class_maps', to='gip.soilclass', verbose_name='Тип почвы'),
        ),
        migrations.AddField(
            model_name='soilclassmap',
            name='soil_class_ky',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_class_maps', to='gip.soilclass', verbose_name='Тип почвы'),
        ),
        migrations.AddField(
            model_name='soilclassmap',
            name='soil_class_ru',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='soil_class_maps', to='gip.soilclass', verbose_name='Тип почвы'),
        ),
    ]
