# Generated by Django 4.1.2 on 2023-03-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0037_soilclassmap_soil_class_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soilclassmap',
            name='soil_class_en',
        ),
        migrations.RemoveField(
            model_name='soilclassmap',
            name='soil_class_ky',
        ),
        migrations.RemoveField(
            model_name='soilclassmap',
            name='soil_class_ru',
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип почвы'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Тип почвы'),
        ),
    ]
