# Generated by Django 4.1.2 on 2023-03-01 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0038_remove_soilclassmap_soil_class_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contouryear',
            name='contour',
        ),
        migrations.AddField(
            model_name='contouryear',
            name='contour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contour_year', to='gip.contour', verbose_name='Контуры полей'),
            preserve_default=False,
        ),
    ]
