# Generated by Django 4.1.2 on 2023-03-09 13:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0039_remove_contouryear_contour_contouryear_contour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elevation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elevation', models.CharField(blank=True, max_length=25, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Контур')),
            ],
        ),
    ]
