# Generated by Django 4.1.2 on 2023-03-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0040_elevation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contouryear',
            name='elevation',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
