# Generated by Django 4.1.2 on 2023-03-16 05:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0042_alter_elevation_options_alter_contouryear_elevation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contouryear',
            name='contour',
        ),
        migrations.RemoveField(
            model_name='contouryear',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='contouryear',
            name='type',
        ),
        migrations.RemoveField(
            model_name='historicalcontouryear',
            name='contour',
        ),
        migrations.RemoveField(
            model_name='historicalcontouryear',
            name='culture',
        ),
        migrations.RemoveField(
            model_name='historicalcontouryear',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalcontouryear',
            name='type',
        ),
        migrations.RemoveField(
            model_name='cropyield',
            name='contour_year',
        ),
        migrations.RemoveField(
            model_name='historicalcropyield',
            name='contour_year',
        ),
        migrations.AddField(
            model_name='contour',
            name='area_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь в гектарах'),
        ),
        migrations.AddField(
            model_name='contour',
            name='culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.culture', verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='contour',
            name='elevation',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='contour',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Контур'),
        ),
        migrations.AddField(
            model_name='contour',
            name='productivity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Продуктивность'),
        ),
        migrations.AddField(
            model_name='contour',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contours', to='gip.landtype', verbose_name='Тип земли'),
        ),
        migrations.AddField(
            model_name='contour',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='cropyield',
            name='contour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='crop_yields', to='gip.contour', verbose_name='Поле'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='area_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь в гектарах'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='culture',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.culture', verbose_name='Культура'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='elevation',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Высота'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Контур'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='productivity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Продуктивность'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.landtype', verbose_name='Тип земли'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='historicalcropyield',
            name='contour',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contour', verbose_name='Поле'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Код СОАТО'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Код СОАТО'),
        ),
    ]
