# Generated by Django 4.1.2 on 2023-03-16 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0026_alter_actualvegindex_contour_and_more'),
        ('gip', '0043_remove_contouryear_contour_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContourYear',
        ),
        migrations.DeleteModel(
            name='HistoricalContourYear',
        ),
    ]
