# Generated by Django 4.1.2 on 2023-03-22 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0046_remove_historicalsoilfertility_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contour',
            name='soil_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.soilclass', verbose_name='Тип почвы'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='soil_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.soilclass', verbose_name='Тип почвы'),
        ),
    ]
