# Generated by Django 4.1.2 on 2023-04-03 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0048_alter_district_polygon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='culture',
            name='fill_color',
        ),
        migrations.RemoveField(
            model_name='culture',
            name='stroke_color',
        ),
        migrations.RemoveField(
            model_name='historicalculture',
            name='fill_color',
        ),
        migrations.RemoveField(
            model_name='historicalculture',
            name='stroke_color',
        ),
    ]
