# Generated by Django 4.1.2 on 2023-05-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0050_historicalsoilclass_color_soilclass_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='contour',
            name='predicted_productivity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='predicted_productivity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name=''),
        ),
    ]
