# Generated by Django 4.1.2 on 2023-05-24 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_model', '0006_classes_grouptype_subclass_republicantype_and_more'),
        ('gip', '0051_contour_predicted_productivity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contour',
            name='pasture_culture',
            field=models.ManyToManyField(blank=True, default=None, to='culture_model.pastureculture'),
        ),
    ]
