# Generated by Django 4.1.2 on 2023-05-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_model', '0006_classes_grouptype_subclass_republicantype_and_more'),
        ('gip', '0052_contour_pasture_culture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contour',
            name='pasture_culture',
            field=models.ManyToManyField(blank=True, default=None, help_text='Required if land type is pasture', to='culture_model.pastureculture'),
        ),
    ]
