# Generated by Django 4.1.2 on 2023-06-06 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0053_alter_contour_pasture_culture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalsoilclass',
            old_name='ID',
            new_name='id_soil',
        ),
        migrations.RenameField(
            model_name='soilclass',
            old_name='ID',
            new_name='id_soil',
        ),
    ]
