# Generated by Django 4.1.2 on 2023-06-27 06:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0056_contour_eni_historicalcontour_eni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название Департамента')),
            ],
            options={
                'verbose_name': 'Департамент',
                'verbose_name_plural': 'Департаменты',
            },
        ),
        migrations.CreateModel(
            name='ContactInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование госсортстанций и госсортучастков')),
                ('fullname', models.CharField(max_length=255, verbose_name='ФИО руководителя')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('phone', models.CharField(blank=True, max_length=125, null=True, verbose_name='Телефон')),
                ('mail', models.CharField(blank=True, max_length=125, null=True, verbose_name='Электронный адрес')),
                ('point', django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Адрес на карте')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_information', to='gip.department', verbose_name='Департамент')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_information', to='gip.district', verbose_name='Место расположения')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
            },
        ),
    ]
