# Generated by Django 4.1.2 on 2023-06-29 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0057_department_contactinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinformation',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='address_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование госсортстанций и госсортучастков'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование госсортстанций и госсортучастков'),
        ),
        migrations.AddField(
            model_name='contactinformation',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование госсортстанций и госсортучастков'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название Департамента'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название Департамента'),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название Департамента'),
        ),
    ]
