# Generated by Django 4.1.2 on 2023-07-01 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0058_contactinformation_address_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='unique_code',
            field=models.IntegerField(null=True, unique=True, verbose_name='Уникальный код'),
        ),
    ]
