# Generated by Django 4.1.2 on 2023-08-05 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0059_department_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='conton',
            name='code_soato_vet',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код СОАТО ВЕТ'),
        ),
        migrations.AddField(
            model_name='district',
            name='code_soato_vet',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Код СОАТО ВЕТ'),
        ),
        migrations.AddField(
            model_name='historicalconton',
            name='code_soato_vet',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Код СОАТО ВЕТ'),
        ),
        migrations.AddField(
            model_name='historicaldistrict',
            name='code_soato_vet',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Код СОАТО ВЕТ'),
        ),
    ]
