# Generated by Django 4.1.2 on 2023-08-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0060_conton_code_soato_vet_district_code_soato_vet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contour',
            name='vegetation_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип растительности'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='vegetation_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Тип растительности'),
        ),
    ]
