# Generated by Django 4.1.2 on 2023-09-23 07:53

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('culture_model', '0013_alter_classes_options_alter_decade_options_and_more'),
        ('gip', '0063_contour_vegetation_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
        migrations.AlterModelOptions(
            name='conton',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='contour',
            options={'verbose_name': 'Field Contour', 'verbose_name_plural': 'Field Contours'},
        ),
        migrations.AlterModelOptions(
            name='cropyield',
            options={'verbose_name': 'Crop Yield', 'verbose_name_plural': 'Crop Yields'},
        ),
        migrations.AlterModelOptions(
            name='culture',
            options={'verbose_name': 'Culture', 'verbose_name_plural': 'Cultures'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'District', 'verbose_name_plural': 'Districts'},
        ),
        migrations.AlterModelOptions(
            name='elevation',
            options={'verbose_name': 'Elevation', 'verbose_name_plural': 'Elevations'},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': 'Farmer', 'verbose_name_plural': 'Farmers'},
        ),
        migrations.AlterModelOptions(
            name='historicalconton',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical District', 'verbose_name_plural': 'historical Districts'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontour',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'History', 'verbose_name_plural': 'historical Field Contours'},
        ),
        migrations.AlterModelOptions(
            name='historicalcropyield',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Crop Yield', 'verbose_name_plural': 'historical Crop Yields'},
        ),
        migrations.AlterModelOptions(
            name='historicalculture',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Culture', 'verbose_name_plural': 'historical Cultures'},
        ),
        migrations.AlterModelOptions(
            name='historicaldistrict',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical District', 'verbose_name_plural': 'historical Districts'},
        ),
        migrations.AlterModelOptions(
            name='historicalfarmer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Farmer', 'verbose_name_plural': 'historical Farmers'},
        ),
        migrations.AlterModelOptions(
            name='historicalregion',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Region', 'verbose_name_plural': 'historical Regions'},
        ),
        migrations.AlterModelOptions(
            name='historicalsoilclass',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Soil Type', 'verbose_name_plural': 'historical Soil Types'},
        ),
        migrations.AlterModelOptions(
            name='historicalsoilproductivity',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Soil Productivity', 'verbose_name_plural': 'historical Soil Productivities'},
        ),
        migrations.AlterModelOptions(
            name='landtype',
            options={'verbose_name': 'Land Type', 'verbose_name_plural': 'Land Types'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regions'},
        ),
        migrations.AlterModelOptions(
            name='soilclass',
            options={'verbose_name': 'Soil Type', 'verbose_name_plural': 'Soil Types'},
        ),
        migrations.AlterModelOptions(
            name='soilclassmap',
            options={'verbose_name': 'Soil Type Contour', 'verbose_name_plural': 'Soil Type Contours'},
        ),
        migrations.AlterModelOptions(
            name='soilproductivity',
            options={'verbose_name': 'Soil Productivity', 'verbose_name_plural': 'Soil Productivities'},
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='address_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='address_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='address_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_information', to='gip.department', verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_information', to='gip.district', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='Full Name of Manager'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='mail',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='phone',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='point',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Map Address'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Name of State Seed Stations and State Seed Plots'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of State Seed Stations and State Seed Plots'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of State Seed Stations and State Seed Plots'),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Name of State Seed Stations and State Seed Plots'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='SOATO Code'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='code_soato_vet',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Veterinary SOATO Code'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contons', to='gip.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='name',
            field=models.CharField(max_length=55, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='conton',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='area_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area in Hectares'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SOATO Code'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='conton',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='gip.conton', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.culture', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='elevation',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Elevation'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='eni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ENI'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='farmer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contours', to='gip.farmer', verbose_name='Farmer'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='ink',
            field=models.CharField(blank=True, help_text='Identification Number of the Contour', max_length=100, null=True, verbose_name='INK'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='is_rounded',
            field=models.BooleanField(default=False, verbose_name='Legally Confirmed'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='pasture_culture',
            field=models.ManyToManyField(blank=True, default=None, help_text='Required if land type is pasture', to='culture_model.pastureculture', verbose_name='Pasture Culture'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='predicted_productivity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Predicted Productivity'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='productivity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Productivity'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='soil_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.soilclass', verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contours', to='gip.landtype', verbose_name='Land Type'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='vegetation_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vegetation Type'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_yields', to='gip.contour', verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='culture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_yields', to='gip.culture', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='weight',
            field=models.FloatField(help_text='Measured in centners', verbose_name='Productivity'),
        ),
        migrations.AlterField(
            model_name='cropyield',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='coefficient_crop',
            field=models.FloatField(verbose_name='Crop Productivity Coefficient'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='unique_code',
            field=models.IntegerField(null=True, unique=True, verbose_name='Unique Code'),
        ),
        migrations.AlterField(
            model_name='district',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='SOATO Code'),
        ),
        migrations.AlterField(
            model_name='district',
            name='code_soato_vet',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Veterinary SOATO Code'),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name',
            field=models.CharField(max_length=55, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='district',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='gip.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='district',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='elevation',
            name='elevation',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Elevation'),
        ),
        migrations.AlterField(
            model_name='elevation',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='pin_inn',
            field=models.CharField(help_text='Taxpayer Identification Number or Personal Identification Number', max_length=14, verbose_name='TIN or INN'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmers', to=settings.AUTH_USER_MODEL, verbose_name='Farmer'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='code_soato',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='SOATO Code'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='code_soato_vet',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Veterinary SOATO Code'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='district',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='name',
            field=models.CharField(max_length=55, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='District Name'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='historicalconton',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='area_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area in Hectares'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='SOATO Code'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='conton',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.conton', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='culture',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.culture', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='elevation',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Elevation'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='eni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ENI'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='farmer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.farmer', verbose_name='Farmer'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='ink',
            field=models.CharField(blank=True, help_text='Identification Number of the Contour', max_length=100, null=True, verbose_name='INK'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='is_rounded',
            field=models.BooleanField(default=False, verbose_name='Legally Confirmed'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='predicted_productivity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Predicted Productivity'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='productivity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Productivity'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='soil_class',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.soilclass', verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.landtype', verbose_name='Land Type'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='vegetation_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Vegetation Type'),
        ),
        migrations.AlterField(
            model_name='historicalcontour',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='contour',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contour', verbose_name='Field'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='culture',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.culture', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='season',
            field=models.IntegerField(blank=True, null=True, verbose_name='Season'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='weight',
            field=models.FloatField(help_text='Measured in centners', verbose_name='Productivity'),
        ),
        migrations.AlterField(
            model_name='historicalcropyield',
            name='year',
            field=models.IntegerField(verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='coefficient_crop',
            field=models.FloatField(verbose_name='Crop Productivity Coefficient'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='code_soato',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='SOATO Code'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='code_soato_vet',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Veterinary SOATO Code'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='name',
            field=models.CharField(max_length=55, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='region',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.region', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='historicaldistrict',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='mobile',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='pin_inn',
            field=models.CharField(help_text='Taxpayer Identification Number or Personal Identification Number', max_length=14, verbose_name='TIN or INN'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='historicalfarmer',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Farmer'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='area',
            field=models.IntegerField(verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='code_soato',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='SOATO Code'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='density',
            field=models.FloatField(verbose_name='Density'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='population',
            field=models.IntegerField(verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='historicalregion',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='color',
            field=models.CharField(max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='id_soil',
            field=models.BigIntegerField(verbose_name='Soil ID'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='historicalsoilclass',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Soil Productivity'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Productivity'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Productivity'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Productivity'),
        ),
        migrations.AlterField(
            model_name='historicalsoilproductivity',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Land Type Name'),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='name_en',
            field=models.CharField(max_length=125, null=True, verbose_name='Land Type Name'),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='name_ky',
            field=models.CharField(max_length=125, null=True, verbose_name='Land Type Name'),
        ),
        migrations.AlterField(
            model_name='landtype',
            name='name_ru',
            field=models.CharField(max_length=125, null=True, verbose_name='Land Type Name'),
        ),
        migrations.AlterField(
            model_name='region',
            name='area',
            field=models.IntegerField(verbose_name='Area'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code_soato',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='SOATO Code'),
        ),
        migrations.AlterField(
            model_name='region',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='region',
            name='density',
            field=models.FloatField(verbose_name='Density'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=55, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=55, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ky',
            field=models.CharField(max_length=55, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name_ru',
            field=models.CharField(max_length=55, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='region',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='region',
            name='population',
            field=models.IntegerField(verbose_name='Population'),
        ),
        migrations.AlterField(
            model_name='region',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='color',
            field=models.CharField(max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='id_soil',
            field=models.BigIntegerField(verbose_name='Soil ID'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='soilclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='soilclassmap',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='soilclassmap',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='soilclassmap',
            name='soil_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_class_maps', to='gip.soilclass', verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='soilclassmap',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Soil Productivity'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Productivity'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Productivity'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Soil Productivity'),
        ),
        migrations.AlterField(
            model_name='soilproductivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
    ]
