# Generated by Django 4.1.2 on 2023-09-27 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0064_alter_contactinformation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conton',
            options={'verbose_name': 'Canton', 'verbose_name_plural': 'Cantons'},
        ),
        migrations.AlterModelOptions(
            name='historicalconton',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Canton', 'verbose_name_plural': 'historical Cantons'},
        ),
    ]
