# Generated by Django 4.1.2 on 2023-09-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0065_alter_conton_options_alter_historicalconton_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CultureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('name', models.CharField(max_length=55, verbose_name='Culture type')),
            ],
            options={
                'verbose_name': 'Culture type',
                'verbose_name_plural': 'Cultures types',
            },
        ),
        migrations.AddField(
            model_name='contour',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='month',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='culture',
            name='culture_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='culture_id', to='gip.culturetype', verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='historicalculture',
            name='culture_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.culturetype', verbose_name='Type'),
        ),
    ]
