# Generated by Django 4.1.2 on 2023-09-28 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0066_alter_contour_predicted_productivity_and_more'),
        ('gip', '0066_culturetype_contour_month_historicalcontour_month_and_more'),
    ]

    operations = [
    ]
