# Generated by Django 4.1.2 on 2023-09-28 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0067_merge_20230928_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contour',
            name='month',
        ),
        migrations.RemoveField(
            model_name='historicalcontour',
            name='month',
        ),
        migrations.AddField(
            model_name='contour',
            name='month_of_sowing',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Month of sowing'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='month_of_sowing',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Month of sowing'),
        ),
        migrations.AlterField(
            model_name='culturetype',
            name='name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture type'),
        ),
    ]
