# Generated by Django 4.1.2 on 2023-09-29 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0068_remove_contour_month_remove_historicalcontour_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='coefficient_crop',
            field=models.FloatField(blank=True, null=True, verbose_name='Crop Productivity Coefficient'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='culture_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='culture_id', to='gip.culturetype', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name_en',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name_ky',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='culture',
            name='name_ru',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='coefficient_crop',
            field=models.FloatField(blank=True, null=True, verbose_name='Crop Productivity Coefficient'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name_en',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name_ky',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='historicalculture',
            name='name_ru',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture'),
        ),
    ]
