# Generated by Django 4.1.2 on 2023-09-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0069_alter_culture_coefficient_crop_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='culturetype',
            name='name_en',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture type'),
        ),
        migrations.AddField(
            model_name='culturetype',
            name='name_ky',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture type'),
        ),
        migrations.AddField(
            model_name='culturetype',
            name='name_ru',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Culture type'),
        ),
    ]
