# Generated by Django 4.1.2 on 2023-10-06 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0071_alter_contour_conton_alter_culture_coefficient_crop_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Elevation',
        ),
    ]
