# Generated by Django 4.1.2 on 2023-11-24 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0073_contour_cadastre_historicalcontour_cadastre'),
    ]

    operations = [
        migrations.AddField(
            model_name='contour',
            name='predicted_culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_predicted_culture', to='gip.culture', verbose_name='Predicted Culture'),
        ),
        migrations.AddField(
            model_name='historicalcontour',
            name='predicted_culture',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.culture', verbose_name='Predicted Culture'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_culture', to='gip.culture', verbose_name='Culture'),
        ),
    ]
