# Generated by Django 4.1.2 on 2022-12-26 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gip', '0010_alter_conton_polygon_alter_contour_polygon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NDVIIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_image', models.FileField(blank=True, upload_to='ndvi_png', verbose_name='Картинка NDVI')),
                ('date_of_satellite_image', models.CharField(choices=[('Весна', 'Весна'), ('Лето', 'Лето'), ('Осень', 'Осень')], max_length=5, verbose_name='Дата космоснимка')),
                ('contour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.contour', verbose_name='Контуры Поля')),
            ],
            options={
                'verbose_name': 'Индекс NDVI',
                'verbose_name_plural': 'Индексы NDVI',
            },
        ),
        migrations.CreateModel(
            name='HistoricalNDVIIndex',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ndvi_image', models.TextField(blank=True, max_length=100, verbose_name='Картинка NDVI')),
                ('date_of_satellite_image', models.CharField(choices=[('Весна', 'Весна'), ('Лето', 'Лето'), ('Осень', 'Осень')], max_length=5, verbose_name='Дата космоснимка')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contour', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contour', verbose_name='Контуры Поля')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'historical Индексы NDVI',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
