# Generated by Django 4.1.2 on 2023-01-10 11:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gip', '0011_culture_fill_color_culture_stroke_color_and_more'),
        ('culture_model', '0002_alter_decade_options_alter_index_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('description', models.TextField(blank=True, help_text='Заполняется при необходимости', null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='дата снимков')),
                ('B01', models.FileField(blank=True, help_text='Coastal aerosol', null=True, upload_to='satellite_images', verbose_name='Слой B01')),
                ('B02', models.FileField(blank=True, help_text='Blue', null=True, upload_to='satellite_images', verbose_name='Слой B02')),
                ('B03', models.FileField(blank=True, help_text='Green', null=True, upload_to='satellite_images', verbose_name='Слой B03')),
                ('B04', models.FileField(blank=True, help_text='Red', null=True, upload_to='satellite_images', verbose_name='Слой B04')),
                ('B05', models.FileField(blank=True, help_text='Vegetation red edge', null=True, upload_to='satellite_images', verbose_name='Слой B05')),
                ('B06', models.FileField(blank=True, help_text='Vegetation red edge', null=True, upload_to='satellite_images', verbose_name='Слой B06')),
                ('B07', models.FileField(blank=True, help_text='Vegetation red edge', null=True, upload_to='satellite_images', verbose_name='Слой B07')),
                ('B08', models.FileField(blank=True, help_text='NIR', null=True, upload_to='satellite_images', verbose_name='Слой B08')),
                ('B8A', models.FileField(blank=True, help_text='Narrow NIR', null=True, upload_to='satellite_images', verbose_name='Слой B8A')),
                ('B09', models.FileField(blank=True, help_text='Water vapour', null=True, upload_to='satellite_images', verbose_name='Слой B09')),
                ('B10', models.FileField(blank=True, help_text='SWIR – Cirrus', null=True, upload_to='satellite_images', verbose_name='Слой B10')),
                ('B11', models.FileField(blank=True, help_text='SWIR – 1', null=True, upload_to='satellite_images', verbose_name='Слой B11')),
                ('B12', models.FileField(blank=True, help_text='SWIR - 2', null=True, upload_to='satellite_images', verbose_name='Слой B12')),
            ],
            options={
                'verbose_name': 'Спутниковый снимок',
                'verbose_name_plural': 'Спутниковые снимки',
            },
        ),
        migrations.CreateModel(
            name='NDVIIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ndvi_image', models.FileField(blank=True, upload_to='ndvi_png', verbose_name='Картинка NDVI')),
                ('date_of_satellite_image', models.CharField(choices=[('Весна', '04.05.2022 (Весна)'), ('Лето', '15.07.2022 (Лето)'), ('Осень', '25.09.2022 (Осень)')], max_length=5, verbose_name='Дата космоснимка')),
                ('average_NDVI', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Средий показатель NDVI')),
                ('contour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.contour', verbose_name='Контуры Поля')),
            ],
            options={
                'verbose_name': 'Индекс NDVI',
                'verbose_name_plural': 'Индексы NDVI',
            },
        ),
        migrations.CreateModel(
            name='IndexMeaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_index_value', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MinValueValidator(-1)], verbose_name='Минимальное значение')),
                ('max_index_value', models.DecimalField(decimal_places=3, max_digits=4, validators=[django.core.validators.MaxValueValidator(1)], verbose_name='Максимальное значение')),
                ('description', models.TextField(verbose_name='Описание')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_model.index', verbose_name='Индекс')),
            ],
            options={
                'verbose_name': 'Значение показателя индекса',
                'verbose_name_plural': 'Значение показателей индексов',
            },
        ),
        migrations.CreateModel(
            name='IndexFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_image', models.FileField(blank=True, upload_to='index_image', verbose_name='Картинка индекса')),
                ('average_value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, verbose_name='Средий показатель индекса')),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gip.contour', verbose_name='Контуры Поля')),
                ('decade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_model.decade', verbose_name='Декада')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_model.index', verbose_name='Индекс')),
                ('meaning_of_average_value', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indexes.indexmeaning', verbose_name='Значение среднего показателя')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexes.satelliteimages', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Фактический Индекс',
                'verbose_name_plural': 'Фактические Индексы',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSatelliteImages',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('description', models.TextField(blank=True, help_text='Заполняется при необходимости', null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='дата снимков')),
                ('B01', models.TextField(blank=True, help_text='Coastal aerosol', max_length=100, null=True, verbose_name='Слой B01')),
                ('B02', models.TextField(blank=True, help_text='Blue', max_length=100, null=True, verbose_name='Слой B02')),
                ('B03', models.TextField(blank=True, help_text='Green', max_length=100, null=True, verbose_name='Слой B03')),
                ('B04', models.TextField(blank=True, help_text='Red', max_length=100, null=True, verbose_name='Слой B04')),
                ('B05', models.TextField(blank=True, help_text='Vegetation red edge', max_length=100, null=True, verbose_name='Слой B05')),
                ('B06', models.TextField(blank=True, help_text='Vegetation red edge', max_length=100, null=True, verbose_name='Слой B06')),
                ('B07', models.TextField(blank=True, help_text='Vegetation red edge', max_length=100, null=True, verbose_name='Слой B07')),
                ('B08', models.TextField(blank=True, help_text='NIR', max_length=100, null=True, verbose_name='Слой B08')),
                ('B8A', models.TextField(blank=True, help_text='Narrow NIR', max_length=100, null=True, verbose_name='Слой B8A')),
                ('B09', models.TextField(blank=True, help_text='Water vapour', max_length=100, null=True, verbose_name='Слой B09')),
                ('B10', models.TextField(blank=True, help_text='SWIR – Cirrus', max_length=100, null=True, verbose_name='Слой B10')),
                ('B11', models.TextField(blank=True, help_text='SWIR – 1', max_length=100, null=True, verbose_name='Слой B11')),
                ('B12', models.TextField(blank=True, help_text='SWIR - 2', max_length=100, null=True, verbose_name='Слой B12')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'historical Спутниковые снимки',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNDVIIndex',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('ndvi_image', models.TextField(blank=True, max_length=100, verbose_name='Картинка NDVI')),
                ('date_of_satellite_image', models.CharField(choices=[('Весна', '04.05.2022 (Весна)'), ('Лето', '15.07.2022 (Лето)'), ('Осень', '25.09.2022 (Осень)')], max_length=5, verbose_name='Дата космоснимка')),
                ('average_NDVI', models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Средий показатель NDVI')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contour', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contour', verbose_name='Контуры Поля')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'historical Индексы NDVI',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndexFact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('index_image', models.TextField(blank=True, max_length=100, verbose_name='Картинка индекса')),
                ('average_value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, verbose_name='Средий показатель индекса')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contour', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contour', verbose_name='Контуры Поля')),
                ('decade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='culture_model.decade', verbose_name='Декада')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('index', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='culture_model.index', verbose_name='Индекс')),
                ('meaning_of_average_value', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexes.indexmeaning', verbose_name='Значение среднего показателя')),
                ('source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexes.satelliteimages', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'historical Фактические Индексы',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
