# Generated by Django 4.1.2 on 2022-12-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NDVIIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coordinates', models.FileField(upload_to='coordinates_geojson', verbose_name='Координаты')),
                ('ndvi_image', models.FileField(blank=True, upload_to='ndvi_png', verbose_name='Картинка NDVI')),
            ],
            options={
                'verbose_name': 'Индекс NDVI',
                'verbose_name_plural': 'Индексы NDVI',
            },
        ),
    ]
