# Generated by Django 4.1.2 on 2023-01-04 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalndviindex',
            name='date_of_satellite_image',
            field=models.CharField(choices=[('Весна', '04.05.2022 (Весна)'), ('Лето', '15.07.2022 (Лето)'), ('Осень', '25.09.2022 (Осень)')], max_length=5, verbose_name='Дата космоснимка'),
        ),
        migrations.AlterField(
            model_name='ndviindex',
            name='date_of_satellite_image',
            field=models.CharField(choices=[('Весна', '04.05.2022 (Весна)'), ('Лето', '15.07.2022 (Лето)'), ('Осень', '25.09.2022 (Осень)')], max_length=5, verbose_name='Дата космоснимка'),
        ),
    ]
