# Generated by Django 4.1.2 on 2023-01-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_model', '0002_alter_decade_options_alter_index_options_and_more'),
        ('indexes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalindexfact',
            name='decade',
        ),
        migrations.RemoveField(
            model_name='indexfact',
            name='decade',
        ),
        migrations.AddField(
            model_name='historicalsatelliteimages',
            name='decade',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='culture_model.decade', verbose_name='Декада'),
        ),
        migrations.AddField(
            model_name='satelliteimages',
            name='decade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='culture_model.decade', verbose_name='Декада'),
            preserve_default=False,
        ),
    ]
