# Generated by Django 4.1.2 on 2023-01-05 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0002_alter_historicalndviindex_date_of_satellite_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalndviindex',
            name='average_NDVI',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Средий показатель NDVI'),
        ),
        migrations.AddField(
            model_name='ndviindex',
            name='average_NDVI',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, verbose_name='Средий показатель NDVI'),
        ),
    ]
