# Generated by Django 4.1.2 on 2023-01-06 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('culture_model', '0002_alter_decade_options_alter_index_options_and_more'),
        ('gip', '0011_culture_fill_color_culture_stroke_color_and_more'),
        ('indexes', '0003_historicalndviindex_average_ndvi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('description', models.TextField(blank=True, help_text='Заполняется при необходимости', null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='дата снимков')),
                ('B01', models.FileField(blank=True, help_text='Coastal aerosol', null=True, upload_to='satellite_images', verbose_name='Слой B01')),
                ('B02', models.FileField(blank=True, help_text='Blue', null=True, upload_to='satellite_images', verbose_name='Слой B02')),
                ('B03', models.FileField(blank=True, help_text='Green', null=True, upload_to='satellite_images', verbose_name='Слой B03')),
                ('B04', models.FileField(blank=True, help_text='Red', null=True, upload_to='satellite_images', verbose_name='Слой B04')),
                ('B05', models.FileField(blank=True, help_text='Vegetation red edge', null=True, upload_to='satellite_images', verbose_name='Слой B05')),
                ('B06', models.FileField(blank=True, help_text='Vegetation red edge', null=True, upload_to='satellite_images', verbose_name='Слой B06')),
                ('B07', models.FileField(blank=True, help_text='Vegetation red edge', null=True, upload_to='satellite_images', verbose_name='Слой B07')),
                ('B08', models.FileField(blank=True, help_text='NIR', null=True, upload_to='satellite_images', verbose_name='Слой B08')),
                ('B8A', models.FileField(blank=True, help_text='Narrow NIR', null=True, upload_to='satellite_images', verbose_name='Слой B8A')),
                ('B09', models.FileField(blank=True, help_text='Water vapour', null=True, upload_to='satellite_images', verbose_name='Слой B09')),
                ('B10', models.FileField(blank=True, help_text='SWIR – Cirrus', null=True, upload_to='satellite_images', verbose_name='Слой B10')),
                ('B11', models.FileField(blank=True, help_text='SWIR – 1', null=True, upload_to='satellite_images', verbose_name='Слой B11')),
                ('B12', models.FileField(blank=True, help_text='SWIR - 2', null=True, upload_to='satellite_images', verbose_name='Слой B12')),
            ],
        ),
        migrations.CreateModel(
            name='IndexFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_image', models.FileField(blank=True, null=True, upload_to='index_image', verbose_name='Картинка индекса')),
                ('average_value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Средий показатель индекса')),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gip.contour', verbose_name='Контуры Поля')),
                ('decade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_model.decade', verbose_name='Декада')),
                ('index', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_model.index', verbose_name='Индекс')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexes.satelliteimages', verbose_name='Источник')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSatelliteImages',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100, verbose_name='Название региона')),
                ('description', models.TextField(blank=True, help_text='Заполняется при необходимости', null=True, verbose_name='Описание')),
                ('date', models.DateField(verbose_name='дата снимков')),
                ('B01', models.TextField(blank=True, help_text='Coastal aerosol', max_length=100, null=True, verbose_name='Слой B01')),
                ('B02', models.TextField(blank=True, help_text='Blue', max_length=100, null=True, verbose_name='Слой B02')),
                ('B03', models.TextField(blank=True, help_text='Green', max_length=100, null=True, verbose_name='Слой B03')),
                ('B04', models.TextField(blank=True, help_text='Red', max_length=100, null=True, verbose_name='Слой B04')),
                ('B05', models.TextField(blank=True, help_text='Vegetation red edge', max_length=100, null=True, verbose_name='Слой B05')),
                ('B06', models.TextField(blank=True, help_text='Vegetation red edge', max_length=100, null=True, verbose_name='Слой B06')),
                ('B07', models.TextField(blank=True, help_text='Vegetation red edge', max_length=100, null=True, verbose_name='Слой B07')),
                ('B08', models.TextField(blank=True, help_text='NIR', max_length=100, null=True, verbose_name='Слой B08')),
                ('B8A', models.TextField(blank=True, help_text='Narrow NIR', max_length=100, null=True, verbose_name='Слой B8A')),
                ('B09', models.TextField(blank=True, help_text='Water vapour', max_length=100, null=True, verbose_name='Слой B09')),
                ('B10', models.TextField(blank=True, help_text='SWIR – Cirrus', max_length=100, null=True, verbose_name='Слой B10')),
                ('B11', models.TextField(blank=True, help_text='SWIR – 1', max_length=100, null=True, verbose_name='Слой B11')),
                ('B12', models.TextField(blank=True, help_text='SWIR - 2', max_length=100, null=True, verbose_name='Слой B12')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'historical satellite imagess',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndexFact',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('index_image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Картинка индекса')),
                ('average_value', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Средий показатель индекса')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contour', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contour', verbose_name='Контуры Поля')),
                ('decade', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='culture_model.decade', verbose_name='Декада')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('index', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='culture_model.index', verbose_name='Индекс')),
                ('source', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexes.satelliteimages', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'historical index facts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
