# Generated by Django 4.1.2 on 2023-01-10 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0004_satelliteimages_indexfact_historicalsatelliteimages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalindexfact',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Фактические Индексы'},
        ),
        migrations.AlterModelOptions(
            name='historicalsatelliteimages',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Спутниковые снимки'},
        ),
        migrations.AlterModelOptions(
            name='indexfact',
            options={'verbose_name': 'Фактический Индекс', 'verbose_name_plural': 'Фактические Индексы'},
        ),
        migrations.AlterModelOptions(
            name='satelliteimages',
            options={'verbose_name': 'Спутниковый снимок', 'verbose_name_plural': 'Спутниковые снимки'},
        ),
    ]
