# Generated by Django 4.1.2 on 2023-01-11 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0005_alter_historicalindexfact_date_alter_indexfact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindexfact',
            name='date',
            field=models.DateField(verbose_name='Дата анализа'),
        ),
        migrations.AlterField(
            model_name='indexfact',
            name='date',
            field=models.DateField(verbose_name='Дата анализа'),
        ),
    ]
