# Generated by Django 4.1.2 on 2023-01-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0006_alter_historicalindexfact_date_alter_indexfact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalindexfact',
            name='date',
            field=models.DateField(help_text='Введите дату космо снимка из которого будет высчитан индекс', verbose_name='Дата анализа'),
        ),
        migrations.AlterField(
            model_name='indexfact',
            name='date',
            field=models.DateField(help_text='Введите дату космо снимка из которого будет высчитан индекс', verbose_name='Дата анализа'),
        ),
    ]
