# Generated by Django 4.1.2 on 2023-01-11 14:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0008_remove_ndviindex_contour_delete_historicalndviindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsatelliteimages',
            name='bbox',
            field=models.CharField(default=datetime.date(2022, 3, 4), max_length=255, verbose_name='Координаты снимков'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='satelliteimages',
            name='bbox',
            field=models.CharField(default=1, max_length=255, verbose_name='Координаты снимков'),
            preserve_default=False,
        ),
    ]
