# Generated by Django 4.1.2 on 2023-01-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0012_rename_indexfact_actuavegindex_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contouraverageindex',
            name='index_count',
            field=models.IntegerField(default=None, verbose_name='Колличество индексов использованных для подсчёта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcontouraverageindex',
            name='index_count',
            field=models.IntegerField(default=None, verbose_name='Колличество индексов использованных для подсчёта'),
            preserve_default=False,
        ),
    ]
