# Generated by Django 4.1.2 on 2023-01-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0013_contouraverageindex_index_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contouraverageindex',
            options={'verbose_name': 'Средний индек контура', 'verbose_name_plural': 'Средние индесы контуров'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontouraverageindex',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Средние индесы контуров'},
        ),
        migrations.AlterModelOptions(
            name='historicalproductivityclass',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Классы продуктивности'},
        ),
        migrations.AlterModelOptions(
            name='productivityclass',
            options={'verbose_name': 'Класс продуктивности', 'verbose_name_plural': 'Классы продуктивности'},
        ),
    ]
