# Generated by Django 4.1.2 on 2023-01-23 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0014_alter_contouraverageindex_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteImageBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band_name', models.CharField(max_length=255, unique=True, verbose_name='Название диапазона спутникового снимка')),
                ('band_description', models.TextField(verbose_name='Описание диапазона спутникового снимка')),
            ],
            options={
                'verbose_name': 'Диапазон спутникового снимка',
                'verbose_name_plural': 'Диапазоны спутникового снимка',
            },
        ),
        migrations.CreateModel(
            name='SatelliteImageSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Источник спутниковых снимков',
                'verbose_name_plural': 'Источники Спутниковых снимков',
            },
        ),
        migrations.CreateModel(
            name='SatelliteImageLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='satellite_image', verbose_name='Снимок')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_band', to='indexes.satelliteimageband', verbose_name='Диапазон спутникового снимка')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_source', to='indexes.satelliteimagesource', verbose_name='Источник спутниковых снимков')),
            ],
            options={
                'verbose_name': 'Слой спутникового снимка',
                'verbose_name_plural': 'Слои спутниковых снимков',
            },
        ),
    ]
