# Generated by Django 4.1.2 on 2023-02-07 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0018_alter_contouryear_options_remove_cropyield_contour_and_more'),
        ('indexes', '0015_satelliteimageband_satelliteimagesource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuavegindex',
            name='contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gip.contouryear', verbose_name='Контуры Поля'),
        ),
        migrations.AlterField(
            model_name='historicalactuavegindex',
            name='contour',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contouryear', verbose_name='Контуры Поля'),
        ),
    ]
