# Generated by Django 4.1.2 on 2023-02-09 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0019_alter_contouryear_contour_alter_contouryear_type'),
        ('indexes', '0016_alter_actuavegindex_contour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contouraverageindex',
            name='contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gip.contouryear', verbose_name='Контуры Поля'),
        ),
        migrations.AlterField(
            model_name='historicalcontouraverageindex',
            name='contour',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contouryear', verbose_name='Контуры Поля'),
        ),
    ]
