# Generated by Django 4.1.2 on 2023-02-20 07:43

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('indexes', '0018_actualvegindex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SciHubAreaInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Область интересов')),
            ],
        ),
        migrations.CreateModel(
            name='SciHubImageDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата снимков')),
                ('B01', models.FileField(blank=True, help_text='Coastal aerosol', null=True, upload_to='satellite_images', verbose_name='Слой B01')),
                ('B02', models.FileField(blank=True, help_text='Blue', null=True, upload_to='satellite_images', verbose_name='Слой B02')),
                ('B03', models.FileField(blank=True, help_text='Green', null=True, upload_to='satellite_images', verbose_name='Слой B03')),
                ('B04', models.FileField(blank=True, help_text='Red', null=True, upload_to='satellite_images', verbose_name='Слой B04')),
                ('B05', models.FileField(blank=True, help_text='Vegetation red edge', null=True, upload_to='satellite_images', verbose_name='Слой B05')),
                ('B06', models.FileField(blank=True, help_text='Vegetation red edge', null=True, upload_to='satellite_images', verbose_name='Слой B06')),
                ('B07', models.FileField(blank=True, help_text='Vegetation red edge', null=True, upload_to='satellite_images', verbose_name='Слой B07')),
                ('B08', models.FileField(blank=True, help_text='NIR', null=True, upload_to='satellite_images', verbose_name='Слой B08')),
                ('B8A', models.FileField(blank=True, help_text='Narrow NIR', null=True, upload_to='satellite_images', verbose_name='Слой B8A')),
                ('B09', models.FileField(blank=True, help_text='Water vapour', null=True, upload_to='satellite_images', verbose_name='Слой B09')),
                ('B10', models.FileField(blank=True, help_text='SWIR – Cirrus', null=True, upload_to='satellite_images', verbose_name='Слой B10')),
                ('B11', models.FileField(blank=True, help_text='SWIR – 1', null=True, upload_to='satellite_images', verbose_name='Слой B11')),
                ('B12', models.FileField(blank=True, help_text='SWIR - 2', null=True, upload_to='satellite_images', verbose_name='Слой B12')),
                ('area_interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_date', to='indexes.scihubareainterest')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalSciHubImageDate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='дата снимков')),
                ('B01', models.TextField(blank=True, help_text='Coastal aerosol', max_length=100, null=True, verbose_name='Слой B01')),
                ('B02', models.TextField(blank=True, help_text='Blue', max_length=100, null=True, verbose_name='Слой B02')),
                ('B03', models.TextField(blank=True, help_text='Green', max_length=100, null=True, verbose_name='Слой B03')),
                ('B04', models.TextField(blank=True, help_text='Red', max_length=100, null=True, verbose_name='Слой B04')),
                ('B05', models.TextField(blank=True, help_text='Vegetation red edge', max_length=100, null=True, verbose_name='Слой B05')),
                ('B06', models.TextField(blank=True, help_text='Vegetation red edge', max_length=100, null=True, verbose_name='Слой B06')),
                ('B07', models.TextField(blank=True, help_text='Vegetation red edge', max_length=100, null=True, verbose_name='Слой B07')),
                ('B08', models.TextField(blank=True, help_text='NIR', max_length=100, null=True, verbose_name='Слой B08')),
                ('B8A', models.TextField(blank=True, help_text='Narrow NIR', max_length=100, null=True, verbose_name='Слой B8A')),
                ('B09', models.TextField(blank=True, help_text='Water vapour', max_length=100, null=True, verbose_name='Слой B09')),
                ('B10', models.TextField(blank=True, help_text='SWIR – Cirrus', max_length=100, null=True, verbose_name='Слой B10')),
                ('B11', models.TextField(blank=True, help_text='SWIR – 1', max_length=100, null=True, verbose_name='Слой B11')),
                ('B12', models.TextField(blank=True, help_text='SWIR - 2', max_length=100, null=True, verbose_name='Слой B12')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('area_interest', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexes.scihubareainterest')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'История',
                'verbose_name_plural': 'historical sci hub image dates',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
