# Generated by Django 4.1.2 on 2023-02-20 08:15

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0019_scihubareainterest_scihubimagedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscihubimagedate',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Координат Снимка'),
        ),
        migrations.AddField(
            model_name='scihubimagedate',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Координат Снимка'),
        ),
        migrations.AlterField(
            model_name='scihubareainterest',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(geography='Kyrgyzstan', srid=4326, verbose_name='Область интереса'),
        ),
    ]
