# Generated by Django 4.1.2 on 2023-02-24 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0022_alter_indexcreatingreport_satellite_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalproductivityclass',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Класс продуктивности', 'verbose_name_plural': 'historical Классы продуктивности'},
        ),
        migrations.AddField(
            model_name='historicalproductivityclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicalproductivityclass',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicalproductivityclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='historicalproductivityclass',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='historicalproductivityclass',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='historicalproductivityclass',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='indexcreatingreport',
            name='process_error_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indexcreatingreport',
            name='process_error_ky',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indexcreatingreport',
            name='process_error_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='indexmeaning',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='indexmeaning',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='indexmeaning',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productivityclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productivityclass',
            name='description_ky',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productivityclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='productivityclass',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='productivityclass',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='productivityclass',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='satelliteimageband',
            name='band_description_en',
            field=models.TextField(null=True, verbose_name='Описание диапазона спутникового снимка'),
        ),
        migrations.AddField(
            model_name='satelliteimageband',
            name='band_description_ky',
            field=models.TextField(null=True, verbose_name='Описание диапазона спутникового снимка'),
        ),
        migrations.AddField(
            model_name='satelliteimageband',
            name='band_description_ru',
            field=models.TextField(null=True, verbose_name='Описание диапазона спутникового снимка'),
        ),
        migrations.AddField(
            model_name='satelliteimageband',
            name='band_name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название диапазона спутникового снимка'),
        ),
        migrations.AddField(
            model_name='satelliteimageband',
            name='band_name_ky',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название диапазона спутникового снимка'),
        ),
        migrations.AddField(
            model_name='satelliteimageband',
            name='band_name_ru',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='Название диапазона спутникового снимка'),
        ),
        migrations.AddField(
            model_name='satelliteimagesource',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='satelliteimagesource',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='satelliteimagesource',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='satelliteimagesource',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='satelliteimagesource',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
        migrations.AddField(
            model_name='satelliteimagesource',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Наименование'),
        ),
    ]
