# Generated by Django 4.1.2 on 2023-02-28 04:44

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_model', '0005_alter_decade_options_alter_indexplan_options_and_more'),
        ('gip', '0030_alter_conton_options_alter_contour_options_and_more'),
        ('indexes', '0023_alter_historicalproductivityclass_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contouraverageindex',
            options={'verbose_name': 'Средний индекc контура', 'verbose_name_plural': 'Средние индексы контуров'},
        ),
        migrations.AlterModelOptions(
            name='historicalcontouraverageindex',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Средние индексы контуров'},
        ),
        migrations.AlterModelOptions(
            name='historicalsatelliteimages',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Спутниковые снимки Sentinel -2 beta'},
        ),
        migrations.AlterModelOptions(
            name='historicalscihubimagedate',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Спутниковые снимки Sentinel -2'},
        ),
        migrations.AlterModelOptions(
            name='indexcreatingreport',
            options={'verbose_name': 'Отчет по индексу', 'verbose_name_plural': 'Отчеты по индексу'},
        ),
        migrations.AlterModelOptions(
            name='satelliteimages',
            options={'verbose_name': 'Спутниковый снимок Sentinel -2 beta', 'verbose_name_plural': 'Спутниковые снимки Sentinel -2 beta'},
        ),
        migrations.AlterModelOptions(
            name='satelliteimagesource',
            options={'verbose_name': 'Источник спутниковых снимков', 'verbose_name_plural': 'Источники спутниковых снимков'},
        ),
        migrations.AlterModelOptions(
            name='scihubareainterest',
            options={'verbose_name': 'Область интереса спутникового снимка', 'verbose_name_plural': 'Области интереса спутникового снимка'},
        ),
        migrations.AlterModelOptions(
            name='scihubimagedate',
            options={'verbose_name': 'Спутниковый снимок Sentinel -2', 'verbose_name_plural': 'Спутниковые снимки Sentinel -2'},
        ),
        migrations.AlterField(
            model_name='actualvegindex',
            name='average_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, verbose_name='Средний показатель индекса'),
        ),
        migrations.AlterField(
            model_name='actualvegindex',
            name='contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_veg_index', to='gip.contouryear', verbose_name='Контуры поля'),
        ),
        migrations.AlterField(
            model_name='actualvegindex',
            name='index_image',
            field=models.FileField(blank=True, upload_to='index_image', verbose_name='Изображение индекса'),
        ),
        migrations.AlterField(
            model_name='actualvegindex',
            name='meaning_of_average_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indexes.indexmeaning', verbose_name='Средний показатель индекса'),
        ),
        migrations.AlterField(
            model_name='contouraverageindex',
            name='contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gip.contouryear', verbose_name='Контуры поля'),
        ),
        migrations.AlterField(
            model_name='contouraverageindex',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, verbose_name='Средний показатель индекса'),
        ),
        migrations.AlterField(
            model_name='historicalactualvegindex',
            name='average_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, verbose_name='Средний показатель индекса'),
        ),
        migrations.AlterField(
            model_name='historicalactualvegindex',
            name='contour',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contouryear', verbose_name='Контуры поля'),
        ),
        migrations.AlterField(
            model_name='historicalactualvegindex',
            name='index_image',
            field=models.TextField(blank=True, max_length=100, verbose_name='Изображение индекса'),
        ),
        migrations.AlterField(
            model_name='historicalactualvegindex',
            name='meaning_of_average_value',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexes.indexmeaning', verbose_name='Средний показатель индекса'),
        ),
        migrations.AlterField(
            model_name='historicalcontouraverageindex',
            name='contour',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='gip.contouryear', verbose_name='Контуры поля'),
        ),
        migrations.AlterField(
            model_name='historicalcontouraverageindex',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, verbose_name='Средний показатель индекса'),
        ),
        migrations.AlterField(
            model_name='historicalproductivityclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalproductivityclass',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalproductivityclass',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalproductivityclass',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='historicalscihubimagedate',
            name='area_interest',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexes.scihubareainterest', verbose_name='Область интереса'),
        ),
        migrations.AlterField(
            model_name='historicalscihubimagedate',
            name='date',
            field=models.DateTimeField(verbose_name='Дата снимков'),
        ),
        migrations.AlterField(
            model_name='historicalscihubimagedate',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Координаты снимка'),
        ),
        migrations.AlterField(
            model_name='indexcreatingreport',
            name='contour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.contouryear', verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='indexcreatingreport',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Обрабатывается'),
        ),
        migrations.AlterField(
            model_name='indexcreatingreport',
            name='process_error',
            field=models.TextField(verbose_name='Ошибки обработки'),
        ),
        migrations.AlterField(
            model_name='indexcreatingreport',
            name='process_error_en',
            field=models.TextField(null=True, verbose_name='Ошибки обработки'),
        ),
        migrations.AlterField(
            model_name='indexcreatingreport',
            name='process_error_ky',
            field=models.TextField(null=True, verbose_name='Ошибки обработки'),
        ),
        migrations.AlterField(
            model_name='indexcreatingreport',
            name='process_error_ru',
            field=models.TextField(null=True, verbose_name='Ошибки обработки'),
        ),
        migrations.AlterField(
            model_name='indexcreatingreport',
            name='satellite_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indexes.scihubimagedate', verbose_name='Спутниковое изображение'),
        ),
        migrations.AlterField(
            model_name='indexcreatingreport',
            name='veg_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='culture_model.vegetationindex', verbose_name='Вегетативный индекс'),
        ),
        migrations.AlterField(
            model_name='productivityclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productivityclass',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productivityclass',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='productivityclass',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='satelliteimagesource',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='satelliteimagesource',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='satelliteimagesource',
            name='name_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='satelliteimagesource',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='scihubimagedate',
            name='area_interest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_date', to='indexes.scihubareainterest', verbose_name='Область интереса'),
        ),
        migrations.AlterField(
            model_name='scihubimagedate',
            name='date',
            field=models.DateTimeField(verbose_name='Дата снимков'),
        ),
        migrations.AlterField(
            model_name='scihubimagedate',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Координаты снимка'),
        ),
    ]
