# Generated by Django 4.1.2 on 2023-02-28 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_model', '0005_alter_decade_options_alter_indexplan_options_and_more'),
        ('indexes', '0024_alter_contouraverageindex_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexcreatingreport',
            name='veg_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='culture_model.vegetationindex', verbose_name='Вегетационный индекс'),
        ),
    ]
