# Generated by Django 4.1.2 on 2023-03-24 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0026_alter_actualvegindex_contour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='satelliteimages',
            name='decade',
        ),
        migrations.DeleteModel(
            name='HistoricalSatelliteImages',
        ),
        migrations.DeleteModel(
            name='SatelliteImages',
        ),
    ]
