# Generated by Django 4.1.2 on 2023-04-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0010_alter_ai_found_options_alter_contour_ai_options_and_more'),
        ('culture_model', '0005_alter_decade_options_alter_indexplan_options_and_more'),
        ('indexes', '0028_predictedcontourvegindex_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contouraiindexcreatingreport',
            options={'verbose_name': 'Создание отчета по индексу', 'verbose_name_plural': 'Создание отчетов по индексу'},
        ),
        migrations.AlterModelOptions(
            name='historicalpredictedcontourvegindex',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Прогнозируемые значения показателей индексов'},
        ),
        migrations.AlterModelOptions(
            name='predictedcontourvegindex',
            options={'verbose_name': 'Прогнозируемое значение показателя индекса', 'verbose_name_plural': 'Прогнозируемые значения показателей индексов'},
        ),
        migrations.AlterField(
            model_name='contouraiindexcreatingreport',
            name='contour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.contour_ai', verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='contouraiindexcreatingreport',
            name='is_processed',
            field=models.BooleanField(default=False, verbose_name='Процесс запущен'),
        ),
        migrations.AlterField(
            model_name='contouraiindexcreatingreport',
            name='process_error',
            field=models.TextField(verbose_name='Ошибки обработки'),
        ),
        migrations.AlterField(
            model_name='contouraiindexcreatingreport',
            name='satellite_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indexes.scihubimagedate', verbose_name='Спутниковое изображение'),
        ),
        migrations.AlterField(
            model_name='contouraiindexcreatingreport',
            name='veg_index',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='culture_model.vegetationindex', verbose_name='Вегетационный индекс'),
        ),
        migrations.AlterField(
            model_name='historicalpredictedcontourvegindex',
            name='average_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, verbose_name='Средний показатель индекса'),
        ),
        migrations.AlterField(
            model_name='historicalpredictedcontourvegindex',
            name='contour',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ai.contour_ai', verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='historicalpredictedcontourvegindex',
            name='date',
            field=models.DateField(verbose_name='Дата анализа'),
        ),
        migrations.AlterField(
            model_name='historicalpredictedcontourvegindex',
            name='index',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='culture_model.vegetationindex', verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='historicalpredictedcontourvegindex',
            name='index_image',
            field=models.TextField(blank=True, max_length=100, verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='historicalpredictedcontourvegindex',
            name='meaning_of_average_value',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexes.indexmeaning', verbose_name='Значение показателя индекса'),
        ),
        migrations.AlterField(
            model_name='predictedcontourvegindex',
            name='average_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, verbose_name='Средний показатель индекса'),
        ),
        migrations.AlterField(
            model_name='predictedcontourvegindex',
            name='contour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contour_ai_veg_index', to='ai.contour_ai', verbose_name='Контур'),
        ),
        migrations.AlterField(
            model_name='predictedcontourvegindex',
            name='date',
            field=models.DateField(verbose_name='Дата анализа'),
        ),
        migrations.AlterField(
            model_name='predictedcontourvegindex',
            name='index',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='culture_model.vegetationindex', verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='predictedcontourvegindex',
            name='index_image',
            field=models.FileField(blank=True, upload_to='index_image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='predictedcontourvegindex',
            name='meaning_of_average_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indexes.indexmeaning', verbose_name='Значение показателя индекса'),
        ),
    ]
