# Generated by Django 4.1.2 on 2023-04-12 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0029_alter_contouraiindexcreatingreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalpredictedcontourvegindex',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'История', 'verbose_name_plural': 'historical Значения показателей индексов ИИ'},
        ),
        migrations.AlterModelOptions(
            name='predictedcontourvegindex',
            options={'verbose_name': 'Значение показателя индекса ИИ', 'verbose_name_plural': 'Значения показателей индексов ИИ'},
        ),
    ]
