# Generated by Django 4.1.2 on 2023-04-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0030_alter_historicalpredictedcontourvegindex_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscihubimagedate',
            name='image_png',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='scihubimagedate',
            name='image_png',
            field=models.FileField(blank=True, null=True, upload_to='satellite_images_to_png'),
        ),
    ]
