# Generated by Django 4.1.2 on 2023-04-18 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0032_historicalscihubimagedate_no_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscihubimagedate',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='scihubimagedate',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
