# Generated by Django 4.1.2 on 2023-04-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0035_alter_scihubimagedate_area_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscihubimagedate',
            name='name_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='scihubimagedate',
            name='name_product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
