# Generated by Django 4.1.2 on 2023-04-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0036_historicalscihubimagedate_name_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscihubimagedate',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='scihubimagedate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
