# Generated by Django 4.1.2 on 2023-05-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexes', '0037_historicalscihubimagedate_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalscihubimagedate',
            name='TCI',
            field=models.TextField(blank=True, help_text='RGB', max_length=100, null=True, verbose_name='Слой TCI'),
        ),
        migrations.AddField(
            model_name='scihubimagedate',
            name='TCI',
            field=models.FileField(blank=True, help_text='RGB', null=True, upload_to='satellite_images', verbose_name='Слой TCI'),
        ),
    ]
