# Generated by Django 4.1.2 on 2023-05-29 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('culture_model', '0007_alter_pastureculture_district_type'),
        ('gip', '0053_alter_contour_pasture_culture'),
        ('indexes', '0038_historicalscihubimagedate_tci_scihubimagedate_tci'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualvegindex',
            name='satellite_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='indexes.scihubimagedate'),
        ),
        migrations.AddField(
            model_name='historicalactualvegindex',
            name='satellite_image',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='indexes.scihubimagedate'),
        ),
        migrations.AlterUniqueTogether(
            name='actualvegindex',
            unique_together={('average_value', 'meaning_of_average_value', 'index', 'contour', 'date')},
        ),
    ]
