# Generated by Django 4.1.2 on 2023-04-10 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0004_remove_historicallandinfo_ate2_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytypelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='categorytypelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='documenttypelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='documenttypelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='category_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hub.categorytypelist', verbose_name='Категории земель'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='description',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='document_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hub.documenttypelist', verbose_name='Правоустанавливающие документы'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='land_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hub.landtypelist', verbose_name='Данные по типам угодьев'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='modifiedby',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Кем изменено'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='property_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='hub.propertytypelist', verbose_name='Данные о собственности'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='smcreatorid',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='smownerid',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='status',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_info', to='hub.categorytypelist', verbose_name='Категории земель'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='description',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_info', to='hub.documenttypelist', verbose_name='Правоустанавливающие документы'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='land_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_info', to='hub.landtypelist', verbose_name='Данные по типам угодьев'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='modifiedby',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Кем изменено'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='land_info', to='hub.propertytypelist', verbose_name='Данные о собственности'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='smcreatorid',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='smownerid',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='status',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='landtypelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='landtypelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='propertytypelist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='propertytypelist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
    ]
