# Generated by Django 4.1.2 on 2023-06-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0005_alter_categorytypelist_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallandinfo',
            name='crmid',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Идентификационный номер'),
        ),
        migrations.AlterField(
            model_name='historicallandinfo',
            name='setype',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='crmid',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Идентификационный номер'),
        ),
        migrations.AlterField(
            model_name='landinfo',
            name='setype',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Тип'),
        ),
    ]
