# Generated by Django 4.1.2 on 2023-03-28 04:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Canton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Yolo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai', models.FileField(upload_to='models/')),
            ],
        ),
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326)),
                ('conf', models.FloatField(null=True)),
                ('culture', models.CharField(blank=True, max_length=50)),
                ('productivity', models.CharField(blank=True, max_length=20)),
                ('canton', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='canton', to='ai.canton')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='images', to='ai.images')),
            ],
        ),
    ]
