# Generated by Django 4.1.2 on 2023-03-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_contour_ai_images_ai_alter_yolo_ai_delete_contour_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityML',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('ml_model', models.FileField(upload_to='productivity/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
