# Generated by Django 4.1.2 on 2023-04-04 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0049_remove_culture_fill_color_and_more'),
        ('ai', '0005_contour_ai_area_ha_contour_ai_elevation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contour_ai',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_ai', to='gip.landtype', verbose_name='Тип земли'),
        ),
    ]
