# Generated by Django 4.1.2 on 2023-04-07 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0049_remove_culture_fill_color_and_more'),
        ('ai', '0009_ai_found_create_rgb_cut_rgb_tif_merge_bands_process'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ai_found',
            options={'verbose_name': 'Процесс поиска контуров', 'verbose_name_plural': 'Процесс поиска контуров'},
        ),
        migrations.AlterModelOptions(
            name='contour_ai',
            options={'verbose_name': 'Контур найденный ИИ', 'verbose_name_plural': 'Контуры найденные ИИ'},
        ),
        migrations.AlterModelOptions(
            name='create_rgb',
            options={'verbose_name': 'Процесс создание цветных изображений', 'verbose_name_plural': 'Процесс создание цветных изображений'},
        ),
        migrations.AlterModelOptions(
            name='cut_rgb_tif',
            options={'verbose_name': 'Процесс обрезания цветных изображений', 'verbose_name_plural': 'Процесс обрезания цветных изображений'},
        ),
        migrations.AlterModelOptions(
            name='dataset',
            options={'verbose_name': 'Датасет', 'verbose_name_plural': 'Датасеты'},
        ),
        migrations.AlterModelOptions(
            name='images_ai',
            options={'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AlterModelOptions(
            name='merge_bands',
            options={'verbose_name': 'Процесс сбора изображений', 'verbose_name_plural': 'Процесс сбора изображений'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Процесс', 'verbose_name_plural': 'Процесс'},
        ),
        migrations.AlterModelOptions(
            name='productivityml',
            options={'verbose_name': 'Модель для прогноза продуктивности', 'verbose_name_plural': 'Модели для прогноза продуктивности'},
        ),
        migrations.AlterModelOptions(
            name='yolo',
            options={'verbose_name': 'Модель для поиска контуров', 'verbose_name_plural': 'Модели для поиска контуров'},
        ),
        migrations.AlterField(
            model_name='ai_found',
            name='is_passed',
            field=models.BooleanField(verbose_name='Завершен'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_ai', to='gip.district', verbose_name='Район'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_ai', to='ai.images_ai', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Процент'),
        ),
        migrations.AlterField(
            model_name='create_rgb',
            name='is_passed',
            field=models.BooleanField(verbose_name='Завершен'),
        ),
        migrations.AlterField(
            model_name='create_rgb',
            name='type_of_process',
            field=models.IntegerField(verbose_name='Номер процесса'),
        ),
        migrations.AlterField(
            model_name='cut_rgb_tif',
            name='is_passed',
            field=models.BooleanField(verbose_name='Завершен'),
        ),
        migrations.AlterField(
            model_name='cut_rgb_tif',
            name='type_of_process',
            field=models.IntegerField(verbose_name='Номер процесса'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='zip',
            field=models.FileField(upload_to='zip/', verbose_name='Датасет'),
        ),
        migrations.AlterField(
            model_name='images_ai',
            name='image',
            field=models.ImageField(blank=True, upload_to='images_ai', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='merge_bands',
            name='is_passed',
            field=models.BooleanField(verbose_name='Завершен'),
        ),
        migrations.AlterField(
            model_name='merge_bands',
            name='type_of_process',
            field=models.IntegerField(verbose_name='Номер процесса'),
        ),
        migrations.AlterField(
            model_name='process',
            name='is_running',
            field=models.BooleanField(verbose_name='Выполняется'),
        ),
        migrations.AlterField(
            model_name='process',
            name='type_of_process',
            field=models.IntegerField(verbose_name='Номер процесса'),
        ),
        migrations.AlterField(
            model_name='productivityml',
            name='ml_model',
            field=models.FileField(upload_to='productivity/', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='yolo',
            name='ai',
            field=models.FileField(upload_to='models_ai/', verbose_name='Модель'),
        ),
    ]
