# Generated by Django 4.1.2 on 2023-04-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0011_createdescription'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='createdescription',
            options={'verbose_name': 'Инструкция создания датасета', 'verbose_name_plural': 'Инструкция создания датасета'},
        ),
        migrations.AlterField(
            model_name='createdescription',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
