# Generated by Django 4.1.2 on 2023-04-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0012_alter_createdescription_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createdescription',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='createdescription',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='createdescription',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
    ]
