# Generated by Django 4.1.2 on 2023-09-23 07:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gip', '0063_contour_vegetation_type_and_more'),
        ('ai', '0014_alter_dataset_options_alter_dataset_zip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ai_found',
            options={'verbose_name': 'Contour search process', 'verbose_name_plural': 'Contour search process'},
        ),
        migrations.AlterModelOptions(
            name='contour_ai',
            options={'verbose_name': 'AI Detected Contour', 'verbose_name_plural': 'AI Detected Contours'},
        ),
        migrations.AlterModelOptions(
            name='create_rgb',
            options={'verbose_name': 'The process of creating color images', 'verbose_name_plural': 'The process of creating color images'},
        ),
        migrations.AlterModelOptions(
            name='createdescription',
            options={'verbose_name': 'Instructions for creating a dataset', 'verbose_name_plural': 'Instructions for creating a dataset'},
        ),
        migrations.AlterModelOptions(
            name='cut_rgb_tif',
            options={'verbose_name': 'Process of cropping color images', 'verbose_name_plural': 'Process of cropping color images'},
        ),
        migrations.AlterModelOptions(
            name='images_ai',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='merge_bands',
            options={'verbose_name': 'Image collection process', 'verbose_name_plural': 'Image collection process'},
        ),
        migrations.AlterModelOptions(
            name='process',
            options={'verbose_name': 'Process', 'verbose_name_plural': 'Processes'},
        ),
        migrations.AlterModelOptions(
            name='productivityml',
            options={'verbose_name': 'Productivity Prediction Model', 'verbose_name_plural': 'Productivity Prediction Models'},
        ),
        migrations.AlterModelOptions(
            name='yolo',
            options={'verbose_name': 'Contour Detection Model', 'verbose_name_plural': 'Contour Detection Models'},
        ),
        migrations.AlterField(
            model_name='ai_found',
            name='is_passed',
            field=models.BooleanField(verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='area_ha',
            field=models.FloatField(blank=True, null=True, verbose_name='Area in hectares'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='conton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_ai', to='gip.conton', verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='culture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.culture', verbose_name='Culture'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_ai', to='gip.district', verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='elevation',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Elevation'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_ai', to='ai.images_ai', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='polygon',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, geography='Kyrgyzstan', null=True, srid=4326, verbose_name='Contour'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='productivity',
            field=models.CharField(blank=True, max_length=20, verbose_name='Productivity'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='soil_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gip.soilclass', verbose_name='Soil Type'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contour_ai', to='gip.landtype', verbose_name='Land type'),
        ),
        migrations.AlterField(
            model_name='contour_ai',
            name='year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Year'),
        ),
        migrations.AlterField(
            model_name='create_rgb',
            name='is_passed',
            field=models.BooleanField(verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='create_rgb',
            name='type_of_process',
            field=models.IntegerField(verbose_name='Process number'),
        ),
        migrations.AlterField(
            model_name='createdescription',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='createdescription',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='createdescription',
            name='description_ky',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='createdescription',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cut_rgb_tif',
            name='is_passed',
            field=models.BooleanField(verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='cut_rgb_tif',
            name='type_of_process',
            field=models.IntegerField(verbose_name='Process number'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='images_ai',
            name='image',
            field=models.ImageField(blank=True, upload_to='images_ai', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='merge_bands',
            name='is_passed',
            field=models.BooleanField(verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='merge_bands',
            name='type_of_process',
            field=models.IntegerField(verbose_name='Process number'),
        ),
        migrations.AlterField(
            model_name='process',
            name='is_running',
            field=models.BooleanField(verbose_name='Performed'),
        ),
        migrations.AlterField(
            model_name='process',
            name='type_of_process',
            field=models.IntegerField(verbose_name='Process number'),
        ),
        migrations.AlterField(
            model_name='productivityml',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='productivityml',
            name='ml_model',
            field=models.FileField(upload_to='productivity/', verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='productivityml',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Date'),
        ),
        migrations.AlterField(
            model_name='yolo',
            name='ai',
            field=models.FileField(upload_to='models_ai/', verbose_name='Model'),
        ),
    ]
